proc getlistofprojectparam {} {
	set projparamlist [list \
    "BOOT.PMC.OSC_FREQ" \
    "BOOT.PMC.OSPI_ENABLE" \
    "BOOT.PMC.OSPI_FREQ" \
    "BOOT.PMC.QSPI_ENABLE" \
    "BOOT.PMC.QSPI_BUS_WIDTH" \
    "BOOT.PMC.QSPI_DATA_MODE" \
    "BOOT.PMC.QSPI_FB_CLK" \
    "BOOT.PMC.QSPI_FREQ" \
    "BOOT.PMC.SD0_DATA_TRANSFER_MODE" \
    "BOOT.PMC.SD0_ENABLE" \
    "BOOT.PMC.SD0_FREQ" \
    "BOOT.PMC.SD0_SLOT_TYPE" \
    "BOOT.PMC.SD1_DATA_TRANSFER_MODE" \
    "BOOT.PMC.SD1_ENABLE" \
    "BOOT.PMC.SD1_FREQ" \
    "BOOT.PMC.SD1_SLOT_TYPE" \
    "BOOT.PMC.SMAP_ENABLE" \
    "BOOT.USB_ENABLE" \
    "BOOT.PMC.SMAP_DATA_WIDTH" \
    "BOOT.SECONDARY.PCIE_ENABLE" 
  ]
}  
