// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xber_kernel.h"

extern XBer_kernel_Config XBer_kernel_ConfigTable[];

XBer_kernel_Config *XBer_kernel_LookupConfig(u16 DeviceId) {
	XBer_kernel_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBER_KERNEL_NUM_INSTANCES; Index++) {
		if (XBer_kernel_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBer_kernel_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBer_kernel_Initialize(XBer_kernel *InstancePtr, u16 DeviceId) {
	XBer_kernel_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBer_kernel_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBer_kernel_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

