// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module awgn_real (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        snr_V,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [7:0] snr_V;
output  [17:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
reg   [127:0] chan_real_noise_lfsr;
wire   [8:0] coarseContents308_address0;
reg    coarseContents308_ce0;
wire   [16:0] coarseContents308_q0;
wire   [8:0] coarseContents308_address1;
reg    coarseContents308_ce1;
wire   [16:0] coarseContents308_q1;
wire   [8:0] coarseContents308_address2;
reg    coarseContents308_ce2;
wire   [16:0] coarseContents308_q2;
wire   [8:0] coarseContents308_address3;
reg    coarseContents308_ce3;
wire   [16:0] coarseContents308_q3;
wire   [8:0] gradientContents_address0;
reg    gradientContents_ce0;
wire   [12:0] gradientContents_q0;
wire   [8:0] gradientContents_address1;
reg    gradientContents_ce1;
wire   [12:0] gradientContents_q1;
wire   [8:0] gradientContents_address2;
reg    gradientContents_ce2;
wire   [12:0] gradientContents_q2;
wire   [8:0] gradientContents_address3;
reg    gradientContents_ce3;
wire   [12:0] gradientContents_q3;
wire   [7:0] scaleLookup_address0;
reg    scaleLookup_ce0;
wire   [16:0] scaleLookup_q0;
reg   [7:0] snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter1_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter2_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter3_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter4_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter5_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter6_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter7_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter8_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter9_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter10_snr_V_read_reg_1614;
reg   [7:0] ap_reg_pp0_iter11_snr_V_read_reg_1614;
reg   [127:0] p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter1_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter2_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter3_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter4_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter5_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter6_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter7_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter8_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter9_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter10_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter11_p_Val2_s_reg_1619;
reg   [127:0] ap_reg_pp0_iter12_p_Val2_s_reg_1619;
wire   [0:0] icmp_fu_320_p2;
reg   [0:0] icmp_reg_1627;
reg   [0:0] ap_reg_pp0_iter1_icmp_reg_1627;
wire   [14:0] norm_V_load_3_0_1_fu_344_p3;
reg   [14:0] norm_V_load_3_0_1_reg_1633;
reg   [3:0] tmp_56_reg_1639;
reg   [4:0] phitmp6128_i_reg_1644;
reg   [4:0] ap_reg_pp0_iter1_phitmp6128_i_reg_1644;
reg   [4:0] ap_reg_pp0_iter2_phitmp6128_i_reg_1644;
wire   [9:0] tmp_69_fu_372_p1;
reg   [9:0] tmp_69_reg_1649;
reg   [9:0] ap_reg_pp0_iter1_tmp_69_reg_1649;
reg   [9:0] ap_reg_pp0_iter2_tmp_69_reg_1649;
reg   [9:0] ap_reg_pp0_iter3_tmp_69_reg_1649;
reg   [9:0] ap_reg_pp0_iter4_tmp_69_reg_1649;
reg  signed [9:0] ap_reg_pp0_iter5_tmp_69_reg_1649;
wire   [0:0] icmp3_fu_396_p2;
reg   [0:0] icmp3_reg_1654;
reg   [0:0] ap_reg_pp0_iter1_icmp3_reg_1654;
wire   [14:0] norm_V_load_3_1_1_fu_420_p3;
reg   [14:0] norm_V_load_3_1_1_reg_1660;
reg   [3:0] tmp_72_reg_1666;
reg   [4:0] phitmp6128_i_1_reg_1671;
reg   [4:0] ap_reg_pp0_iter1_phitmp6128_i_1_reg_1671;
reg   [4:0] ap_reg_pp0_iter2_phitmp6128_i_1_reg_1671;
reg   [9:0] tmp_106_1_reg_1676;
reg   [9:0] ap_reg_pp0_iter1_tmp_106_1_reg_1676;
reg   [9:0] ap_reg_pp0_iter2_tmp_106_1_reg_1676;
reg   [9:0] ap_reg_pp0_iter3_tmp_106_1_reg_1676;
reg   [9:0] ap_reg_pp0_iter4_tmp_106_1_reg_1676;
reg   [9:0] ap_reg_pp0_iter5_tmp_106_1_reg_1676;
reg  signed [9:0] ap_reg_pp0_iter6_tmp_106_1_reg_1676;
wire   [0:0] icmp6_fu_478_p2;
reg   [0:0] icmp6_reg_1681;
reg   [0:0] ap_reg_pp0_iter1_icmp6_reg_1681;
wire   [14:0] norm_V_load_3_2_1_fu_502_p3;
reg   [14:0] norm_V_load_3_2_1_reg_1687;
reg   [3:0] tmp_81_reg_1693;
reg   [4:0] phitmp6128_i_2_reg_1698;
reg   [4:0] ap_reg_pp0_iter1_phitmp6128_i_2_reg_1698;
reg   [4:0] ap_reg_pp0_iter2_phitmp6128_i_2_reg_1698;
reg   [9:0] tmp_106_2_reg_1703;
reg   [9:0] ap_reg_pp0_iter1_tmp_106_2_reg_1703;
reg   [9:0] ap_reg_pp0_iter2_tmp_106_2_reg_1703;
reg   [9:0] ap_reg_pp0_iter3_tmp_106_2_reg_1703;
reg   [9:0] ap_reg_pp0_iter4_tmp_106_2_reg_1703;
reg  signed [9:0] ap_reg_pp0_iter5_tmp_106_2_reg_1703;
wire   [0:0] icmp9_fu_560_p2;
reg   [0:0] icmp9_reg_1708;
reg   [0:0] ap_reg_pp0_iter1_icmp9_reg_1708;
wire   [14:0] norm_V_load_3_3_1_fu_584_p3;
reg   [14:0] norm_V_load_3_3_1_reg_1714;
reg   [3:0] tmp_90_reg_1720;
reg   [4:0] phitmp6128_i_3_reg_1725;
reg   [4:0] ap_reg_pp0_iter1_phitmp6128_i_3_reg_1725;
reg   [4:0] ap_reg_pp0_iter2_phitmp6128_i_3_reg_1725;
reg   [9:0] tmp_106_3_reg_1730;
reg   [9:0] ap_reg_pp0_iter1_tmp_106_3_reg_1730;
reg   [9:0] ap_reg_pp0_iter2_tmp_106_3_reg_1730;
reg   [9:0] ap_reg_pp0_iter3_tmp_106_3_reg_1730;
reg   [9:0] ap_reg_pp0_iter4_tmp_106_3_reg_1730;
reg   [9:0] ap_reg_pp0_iter5_tmp_106_3_reg_1730;
reg   [9:0] ap_reg_pp0_iter6_tmp_106_3_reg_1730;
reg  signed [9:0] ap_reg_pp0_iter7_tmp_106_3_reg_1730;
wire   [0:0] icmp1_fu_756_p2;
reg   [0:0] icmp1_reg_1735;
wire   [14:0] norm_V_load_3_0_2_fu_766_p3;
reg   [14:0] norm_V_load_3_0_2_reg_1740;
reg   [1:0] tmp_61_reg_1746;
wire   [0:0] icmp4_fu_783_p2;
reg   [0:0] icmp4_reg_1751;
wire   [14:0] norm_V_load_3_1_2_fu_793_p3;
reg   [14:0] norm_V_load_3_1_2_reg_1756;
reg   [1:0] tmp_74_reg_1762;
wire   [0:0] icmp7_fu_810_p2;
reg   [0:0] icmp7_reg_1767;
wire   [14:0] norm_V_load_3_2_2_fu_820_p3;
reg   [14:0] norm_V_load_3_2_2_reg_1772;
reg   [1:0] tmp_83_reg_1778;
wire   [0:0] icmp10_fu_837_p2;
reg   [0:0] icmp10_reg_1783;
wire   [14:0] norm_V_load_3_3_2_fu_847_p3;
reg   [14:0] norm_V_load_3_3_2_reg_1788;
reg   [1:0] tmp_92_reg_1794;
wire   [4:0] tmp_68_fu_940_p1;
reg   [4:0] tmp_68_reg_1799;
reg   [3:0] tmp_19_reg_1804;
reg   [3:0] ap_reg_pp0_iter3_tmp_19_reg_1804;
wire   [4:0] tmp_78_fu_1030_p1;
reg   [4:0] tmp_78_reg_1809;
reg   [3:0] tmp_30_reg_1814;
reg   [3:0] ap_reg_pp0_iter3_tmp_30_reg_1814;
reg   [3:0] ap_reg_pp0_iter4_tmp_30_reg_1814;
wire   [4:0] tmp_87_fu_1120_p1;
reg   [4:0] tmp_87_reg_1819;
reg   [3:0] tmp_33_reg_1824;
reg   [3:0] ap_reg_pp0_iter3_tmp_33_reg_1824;
wire   [4:0] tmp_96_fu_1210_p1;
reg   [4:0] tmp_96_reg_1829;
reg   [3:0] tmp_36_reg_1834;
reg   [3:0] ap_reg_pp0_iter3_tmp_36_reg_1834;
reg   [3:0] ap_reg_pp0_iter4_tmp_36_reg_1834;
reg   [3:0] ap_reg_pp0_iter5_tmp_36_reg_1834;
wire   [4:0] tmp_17_fu_1224_p2;
reg   [4:0] tmp_17_reg_1839;
wire   [4:0] tmp_29_fu_1228_p2;
reg   [4:0] tmp_29_reg_1844;
reg   [4:0] ap_reg_pp0_iter4_tmp_29_reg_1844;
wire   [4:0] tmp_32_fu_1232_p2;
reg   [4:0] tmp_32_reg_1849;
wire   [4:0] tmp_35_fu_1236_p2;
reg   [4:0] tmp_35_reg_1854;
reg   [4:0] ap_reg_pp0_iter4_tmp_35_reg_1854;
reg   [4:0] ap_reg_pp0_iter5_tmp_35_reg_1854;
reg   [16:0] coarseContents308_lo_reg_1879;
reg   [16:0] ap_reg_pp0_iter6_coarseContents308_lo_reg_1879;
reg   [16:0] ap_reg_pp0_iter7_coarseContents308_lo_reg_1879;
reg   [16:0] ap_reg_pp0_iter8_coarseContents308_lo_reg_1879;
reg   [16:0] ap_reg_pp0_iter9_coarseContents308_lo_reg_1879;
reg   [12:0] gradientContents_loa_reg_1884;
reg   [16:0] coarseContents308_lo_2_reg_1899;
reg   [16:0] ap_reg_pp0_iter6_coarseContents308_lo_2_reg_1899;
reg   [16:0] ap_reg_pp0_iter7_coarseContents308_lo_2_reg_1899;
reg   [16:0] ap_reg_pp0_iter8_coarseContents308_lo_2_reg_1899;
reg   [16:0] ap_reg_pp0_iter9_coarseContents308_lo_2_reg_1899;
reg   [12:0] gradientContents_loa_2_reg_1904;
reg   [16:0] coarseContents308_lo_1_reg_1919;
reg   [16:0] ap_reg_pp0_iter7_coarseContents308_lo_1_reg_1919;
reg   [16:0] ap_reg_pp0_iter8_coarseContents308_lo_1_reg_1919;
reg   [16:0] ap_reg_pp0_iter9_coarseContents308_lo_1_reg_1919;
reg   [16:0] ap_reg_pp0_iter10_coarseContents308_lo_1_reg_1919;
reg   [12:0] gradientContents_loa_1_reg_1924;
reg   [16:0] coarseContents308_lo_3_reg_1959;
reg   [16:0] ap_reg_pp0_iter8_coarseContents308_lo_3_reg_1959;
reg   [16:0] ap_reg_pp0_iter9_coarseContents308_lo_3_reg_1959;
reg   [16:0] ap_reg_pp0_iter10_coarseContents308_lo_3_reg_1959;
reg   [16:0] ap_reg_pp0_iter11_coarseContents308_lo_3_reg_1959;
reg   [12:0] gradientContents_loa_3_reg_1964;
wire  signed [22:0] grp_fu_1590_p2;
reg  signed [22:0] r_V_s_reg_1979;
wire  signed [22:0] grp_fu_1596_p2;
reg  signed [22:0] r_V_22_2_reg_1984;
wire   [28:0] tmp_22_fu_1326_p2;
reg   [28:0] tmp_22_reg_1989;
wire   [28:0] addconv_i_fu_1332_p2;
reg   [28:0] addconv_i_reg_1994;
wire  signed [22:0] grp_fu_1602_p2;
reg  signed [22:0] r_V_22_1_reg_1999;
wire   [28:0] tmp_114_2_fu_1352_p2;
reg   [28:0] tmp_114_2_reg_2004;
wire   [28:0] addconv_i_2_fu_1358_p2;
reg   [28:0] addconv_i_2_reg_2009;
wire   [28:0] tmp_114_1_fu_1391_p2;
reg   [28:0] tmp_114_1_reg_2014;
wire   [28:0] addconv_i_1_fu_1397_p2;
reg   [28:0] addconv_i_1_reg_2019;
wire  signed [22:0] grp_fu_1608_p2;
reg  signed [22:0] r_V_22_3_reg_2024;
wire   [29:0] tmp_fu_1424_p2;
reg   [29:0] tmp_reg_2029;
wire   [28:0] tmp_114_3_fu_1457_p2;
reg   [28:0] tmp_114_3_reg_2034;
wire   [28:0] addconv_i_3_fu_1463_p2;
reg   [28:0] addconv_i_3_reg_2039;
wire   [29:0] tmp_23_fu_1473_p2;
reg   [29:0] tmp_23_reg_2044;
wire   [30:0] centralLimitNoise_V_fu_1502_p2;
reg  signed [30:0] centralLimitNoise_V_reg_2054;
reg   [16:0] scale_V_reg_2059;
wire   [47:0] grp_fu_1514_p2;
reg   [47:0] r_V_27_reg_2074;
wire   [48:0] r_V_fu_1523_p2;
reg   [48:0] r_V_reg_2079;
reg   [20:0] roundedNoise_V_reg_2084;
reg   [3:0] tmp_101_reg_2089;
wire   [63:0] tmp_20_fu_1246_p1;
wire   [63:0] tmp_107_2_fu_1258_p1;
wire   [63:0] tmp_107_1_fu_1270_p1;
wire   [63:0] tmp_107_3_fu_1294_p1;
wire   [63:0] tmp_24_fu_1478_p1;
wire   [127:0] p_Result_s_fu_742_p3;
wire   [7:0] tmp_55_fu_310_p4;
wire   [6:0] tmp_15_fu_326_p4;
wire   [14:0] tmp_16_fu_336_p3;
wire   [14:0] phitmp6131_i_fu_300_p4;
wire   [7:0] tmp_71_fu_386_p4;
wire   [6:0] tmp_26_fu_402_p4;
wire   [14:0] tmp_134_1_fu_412_p3;
wire   [14:0] phitmp6131_i_1_fu_376_p4;
wire   [7:0] tmp_80_fu_468_p4;
wire   [6:0] tmp_31_fu_484_p4;
wire   [14:0] tmp_134_2_fu_494_p3;
wire   [14:0] phitmp6131_i_2_fu_458_p4;
wire   [7:0] tmp_89_fu_550_p4;
wire   [6:0] tmp_34_fu_566_p4;
wire   [14:0] tmp_134_3_fu_576_p3;
wire   [14:0] phitmp6131_i_3_fu_540_p4;
wire   [29:0] tmp_37_fu_636_p4;
wire   [63:0] r_V_15_fu_646_p3;
wire   [63:0] rhs_V_fu_622_p4;
wire   [63:0] r_V_16_fu_654_p2;
wire   [28:0] r_V_4_fu_660_p4;
wire   [63:0] r_V_17_fu_670_p1;
wire   [63:0] r_V_18_fu_674_p2;
wire   [63:0] r_V_19_fu_680_p2;
wire   [5:0] tmp_99_fu_692_p1;
wire   [63:0] r_V_21_fu_696_p3;
wire   [63:0] rhs_V_3_fu_632_p1;
wire   [63:0] r_V_22_fu_704_p2;
wire   [50:0] r_V_10_fu_710_p4;
wire   [63:0] r_V_23_fu_720_p1;
wire   [63:0] r_V_24_fu_724_p2;
wire   [63:0] r_V_25_fu_730_p2;
wire   [63:0] r_V_20_fu_686_p2;
wire   [63:0] r_V_26_fu_736_p2;
wire   [14:0] tmp_60_fu_761_p2;
wire   [14:0] tmp_73_fu_788_p2;
wire   [14:0] tmp_82_fu_815_p2;
wire   [14:0] tmp_91_fu_842_p2;
wire   [8:0] bramChapter_V_load_1_fu_864_p3;
wire   [8:0] tmp_136_0_s_fu_871_p3;
wire   [8:0] bramChapter_V_load_1_1_fu_878_p3;
wire   [0:0] icmp2_fu_885_p2;
wire   [8:0] tmp_136_0_1_fu_890_p2;
wire   [0:0] tmp_62_fu_904_p3;
wire   [0:0] tmp_66_fu_911_p3;
wire   [8:0] bramChapter_V_load_1_2_fu_896_p3;
wire   [0:0] tmp_67_fu_918_p3;
wire   [8:0] tmp_136_0_3_fu_926_p2;
wire   [8:0] bramChapter_V_load_fu_932_p3;
wire   [8:0] bramChapter_V_load_1_3_fu_954_p3;
wire   [8:0] tmp_136_1_s_fu_961_p3;
wire   [8:0] bramChapter_V_load_1_4_fu_968_p3;
wire   [0:0] icmp5_fu_975_p2;
wire   [8:0] tmp_136_1_1_fu_980_p2;
wire   [0:0] tmp_75_fu_994_p3;
wire   [0:0] tmp_76_fu_1001_p3;
wire   [8:0] bramChapter_V_load_1_5_fu_986_p3;
wire   [0:0] tmp_77_fu_1008_p3;
wire   [8:0] tmp_136_1_3_fu_1016_p2;
wire   [8:0] bramChapter_V_load_s_fu_1022_p3;
wire   [8:0] bramChapter_V_load_1_6_fu_1044_p3;
wire   [8:0] tmp_136_2_s_fu_1051_p3;
wire   [8:0] bramChapter_V_load_1_7_fu_1058_p3;
wire   [0:0] icmp8_fu_1065_p2;
wire   [8:0] tmp_136_2_1_fu_1070_p2;
wire   [0:0] tmp_84_fu_1084_p3;
wire   [0:0] tmp_85_fu_1091_p3;
wire   [8:0] bramChapter_V_load_1_8_fu_1076_p3;
wire   [0:0] tmp_86_fu_1098_p3;
wire   [8:0] tmp_136_2_3_fu_1106_p2;
wire   [8:0] bramChapter_V_load_2_fu_1112_p3;
wire   [8:0] bramChapter_V_load_1_9_fu_1134_p3;
wire   [8:0] tmp_136_3_s_fu_1141_p3;
wire   [8:0] bramChapter_V_load_1_11_fu_1148_p3;
wire   [0:0] icmp11_fu_1155_p2;
wire   [8:0] tmp_136_3_1_fu_1160_p2;
wire   [0:0] tmp_93_fu_1174_p3;
wire   [0:0] tmp_94_fu_1181_p3;
wire   [8:0] bramChapter_V_load_1_10_fu_1166_p3;
wire   [0:0] tmp_95_fu_1188_p3;
wire   [8:0] tmp_136_3_3_fu_1196_p2;
wire   [8:0] bramChapter_V_load_3_fu_1202_p3;
wire   [8:0] tmp_18_fu_1240_p3;
wire   [8:0] tmp_105_2_fu_1252_p3;
wire   [8:0] tmp_105_1_fu_1264_p3;
wire   [8:0] tmp_105_3_fu_1288_p3;
wire   [26:0] r_V_1_fu_1315_p3;
wire  signed [28:0] tmp_21_fu_1312_p1;
wire   [28:0] r_V_23_cast_fu_1322_p1;
wire   [26:0] r_V_23_2_fu_1341_p3;
wire  signed [28:0] tmp_108_2_fu_1338_p1;
wire   [28:0] r_V_23_2_cast_fu_1348_p1;
wire   [0:0] tmp_54_fu_1364_p3;
wire   [26:0] r_V_23_1_fu_1380_p3;
wire  signed [28:0] tmp_108_1_fu_1377_p1;
wire   [28:0] r_V_23_1_cast_fu_1387_p1;
wire   [0:0] tmp_79_fu_1403_p3;
wire   [28:0] noiseGen_V_load_fu_1371_p3;
wire   [28:0] noiseGen_V_load_2_fu_1410_p3;
wire  signed [29:0] tmp_cast_fu_1420_p1;
wire  signed [29:0] p_0202_0_i_cast_fu_1416_p1;
wire   [0:0] tmp_70_fu_1430_p3;
wire   [26:0] r_V_23_3_fu_1446_p3;
wire  signed [28:0] tmp_108_3_fu_1443_p1;
wire   [28:0] r_V_23_3_cast_fu_1453_p1;
wire   [28:0] noiseGen_V_load_1_fu_1437_p3;
wire  signed [29:0] p_0210_0_i_cast_fu_1469_p1;
wire   [0:0] tmp_88_fu_1482_p3;
wire   [28:0] noiseGen_V_load_3_fu_1489_p3;
wire  signed [30:0] tmp_s_fu_1495_p1;
wire  signed [30:0] tmp_69_cast_fu_1499_p1;
wire   [16:0] grp_fu_1514_p0;
wire   [48:0] tmp_25_fu_1520_p1;
wire   [0:0] icmp12_fu_1549_p2;
wire   [0:0] tmp_27_fu_1554_p2;
wire   [0:0] tmp_28_fu_1576_p2;
wire   [17:0] saturatedNoise_V_1_fu_1568_p3;
wire   [17:0] saturatedNoise_V_fu_1559_p4;
wire   [12:0] grp_fu_1590_p1;
wire   [12:0] grp_fu_1596_p1;
wire   [12:0] grp_fu_1602_p1;
wire   [12:0] grp_fu_1608_p1;
reg    grp_fu_1514_ce;
reg    grp_fu_1590_ce;
reg    grp_fu_1596_ce;
reg    grp_fu_1602_ce;
reg    grp_fu_1608_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to19;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [47:0] grp_fu_1514_p00;
wire   [22:0] grp_fu_1590_p10;
wire   [22:0] grp_fu_1596_p10;
wire   [22:0] grp_fu_1602_p10;
wire   [22:0] grp_fu_1608_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 chan_real_noise_lfsr = 128'd1512366075204170930279365292653862641;
end

awgn_real_coarseCjbC #(
    .DataWidth( 17 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
coarseContents308_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(coarseContents308_address0),
    .ce0(coarseContents308_ce0),
    .q0(coarseContents308_q0),
    .address1(coarseContents308_address1),
    .ce1(coarseContents308_ce1),
    .q1(coarseContents308_q1),
    .address2(coarseContents308_address2),
    .ce2(coarseContents308_ce2),
    .q2(coarseContents308_q2),
    .address3(coarseContents308_address3),
    .ce3(coarseContents308_ce3),
    .q3(coarseContents308_q3)
);

awgn_real_gradienkbM #(
    .DataWidth( 13 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
gradientContents_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gradientContents_address0),
    .ce0(gradientContents_ce0),
    .q0(gradientContents_q0),
    .address1(gradientContents_address1),
    .ce1(gradientContents_ce1),
    .q1(gradientContents_q1),
    .address2(gradientContents_address2),
    .ce2(gradientContents_ce2),
    .q2(gradientContents_q2),
    .address3(gradientContents_address3),
    .ce3(gradientContents_ce3),
    .q3(gradientContents_q3)
);

awgn_real_scaleLolbW #(
    .DataWidth( 17 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
scaleLookup_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(scaleLookup_address0),
    .ce0(scaleLookup_ce0),
    .q0(scaleLookup_q0)
);

ber_kernel_mul_17mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 48 ))
ber_kernel_mul_17mb6_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1514_p0),
    .din1(centralLimitNoise_V_reg_2054),
    .ce(grp_fu_1514_ce),
    .dout(grp_fu_1514_p2)
);

ber_kernel_mul_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
ber_kernel_mul_muncg_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_reg_pp0_iter5_tmp_69_reg_1649),
    .din1(grp_fu_1590_p1),
    .ce(grp_fu_1590_ce),
    .dout(grp_fu_1590_p2)
);

ber_kernel_mul_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
ber_kernel_mul_muncg_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_reg_pp0_iter5_tmp_106_2_reg_1703),
    .din1(grp_fu_1596_p1),
    .ce(grp_fu_1596_ce),
    .dout(grp_fu_1596_p2)
);

ber_kernel_mul_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
ber_kernel_mul_muncg_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_reg_pp0_iter6_tmp_106_1_reg_1676),
    .din1(grp_fu_1602_p1),
    .ce(grp_fu_1602_ce),
    .dout(grp_fu_1602_p2)
);

ber_kernel_mul_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
ber_kernel_mul_muncg_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_reg_pp0_iter7_tmp_106_3_reg_1730),
    .din1(grp_fu_1608_p1),
    .ce(grp_fu_1608_ce),
    .dout(grp_fu_1608_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0)))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (~(((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) | (ap_ce == 1'b0))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        chan_real_noise_lfsr <= 128'd1512366075204170930279365292653862641;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1))) begin
            chan_real_noise_lfsr <= p_Result_s_fu_742_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1))) begin
        addconv_i_1_reg_2019 <= addconv_i_1_fu_1397_p2;
        addconv_i_2_reg_2009 <= addconv_i_2_fu_1358_p2;
        addconv_i_3_reg_2039 <= addconv_i_3_fu_1463_p2;
        addconv_i_reg_1994 <= addconv_i_fu_1332_p2;
        ap_reg_pp0_iter10_coarseContents308_lo_1_reg_1919 <= ap_reg_pp0_iter9_coarseContents308_lo_1_reg_1919;
        ap_reg_pp0_iter10_coarseContents308_lo_3_reg_1959 <= ap_reg_pp0_iter9_coarseContents308_lo_3_reg_1959;
        ap_reg_pp0_iter10_p_Val2_s_reg_1619 <= ap_reg_pp0_iter9_p_Val2_s_reg_1619;
        ap_reg_pp0_iter10_snr_V_read_reg_1614 <= ap_reg_pp0_iter9_snr_V_read_reg_1614;
        ap_reg_pp0_iter11_coarseContents308_lo_3_reg_1959 <= ap_reg_pp0_iter10_coarseContents308_lo_3_reg_1959;
        ap_reg_pp0_iter11_p_Val2_s_reg_1619 <= ap_reg_pp0_iter10_p_Val2_s_reg_1619;
        ap_reg_pp0_iter11_snr_V_read_reg_1614 <= ap_reg_pp0_iter10_snr_V_read_reg_1614;
        ap_reg_pp0_iter12_p_Val2_s_reg_1619 <= ap_reg_pp0_iter11_p_Val2_s_reg_1619;
        ap_reg_pp0_iter2_p_Val2_s_reg_1619 <= ap_reg_pp0_iter1_p_Val2_s_reg_1619;
        ap_reg_pp0_iter2_phitmp6128_i_1_reg_1671 <= ap_reg_pp0_iter1_phitmp6128_i_1_reg_1671;
        ap_reg_pp0_iter2_phitmp6128_i_2_reg_1698 <= ap_reg_pp0_iter1_phitmp6128_i_2_reg_1698;
        ap_reg_pp0_iter2_phitmp6128_i_3_reg_1725 <= ap_reg_pp0_iter1_phitmp6128_i_3_reg_1725;
        ap_reg_pp0_iter2_phitmp6128_i_reg_1644 <= ap_reg_pp0_iter1_phitmp6128_i_reg_1644;
        ap_reg_pp0_iter2_snr_V_read_reg_1614 <= ap_reg_pp0_iter1_snr_V_read_reg_1614;
        ap_reg_pp0_iter2_tmp_106_1_reg_1676 <= ap_reg_pp0_iter1_tmp_106_1_reg_1676;
        ap_reg_pp0_iter2_tmp_106_2_reg_1703 <= ap_reg_pp0_iter1_tmp_106_2_reg_1703;
        ap_reg_pp0_iter2_tmp_106_3_reg_1730 <= ap_reg_pp0_iter1_tmp_106_3_reg_1730;
        ap_reg_pp0_iter2_tmp_69_reg_1649 <= ap_reg_pp0_iter1_tmp_69_reg_1649;
        ap_reg_pp0_iter3_p_Val2_s_reg_1619 <= ap_reg_pp0_iter2_p_Val2_s_reg_1619;
        ap_reg_pp0_iter3_snr_V_read_reg_1614 <= ap_reg_pp0_iter2_snr_V_read_reg_1614;
        ap_reg_pp0_iter3_tmp_106_1_reg_1676 <= ap_reg_pp0_iter2_tmp_106_1_reg_1676;
        ap_reg_pp0_iter3_tmp_106_2_reg_1703 <= ap_reg_pp0_iter2_tmp_106_2_reg_1703;
        ap_reg_pp0_iter3_tmp_106_3_reg_1730 <= ap_reg_pp0_iter2_tmp_106_3_reg_1730;
        ap_reg_pp0_iter3_tmp_19_reg_1804 <= tmp_19_reg_1804;
        ap_reg_pp0_iter3_tmp_30_reg_1814 <= tmp_30_reg_1814;
        ap_reg_pp0_iter3_tmp_33_reg_1824 <= tmp_33_reg_1824;
        ap_reg_pp0_iter3_tmp_36_reg_1834 <= tmp_36_reg_1834;
        ap_reg_pp0_iter3_tmp_69_reg_1649 <= ap_reg_pp0_iter2_tmp_69_reg_1649;
        ap_reg_pp0_iter4_p_Val2_s_reg_1619 <= ap_reg_pp0_iter3_p_Val2_s_reg_1619;
        ap_reg_pp0_iter4_snr_V_read_reg_1614 <= ap_reg_pp0_iter3_snr_V_read_reg_1614;
        ap_reg_pp0_iter4_tmp_106_1_reg_1676 <= ap_reg_pp0_iter3_tmp_106_1_reg_1676;
        ap_reg_pp0_iter4_tmp_106_2_reg_1703 <= ap_reg_pp0_iter3_tmp_106_2_reg_1703;
        ap_reg_pp0_iter4_tmp_106_3_reg_1730 <= ap_reg_pp0_iter3_tmp_106_3_reg_1730;
        ap_reg_pp0_iter4_tmp_29_reg_1844 <= tmp_29_reg_1844;
        ap_reg_pp0_iter4_tmp_30_reg_1814 <= ap_reg_pp0_iter3_tmp_30_reg_1814;
        ap_reg_pp0_iter4_tmp_35_reg_1854 <= tmp_35_reg_1854;
        ap_reg_pp0_iter4_tmp_36_reg_1834 <= ap_reg_pp0_iter3_tmp_36_reg_1834;
        ap_reg_pp0_iter4_tmp_69_reg_1649 <= ap_reg_pp0_iter3_tmp_69_reg_1649;
        ap_reg_pp0_iter5_p_Val2_s_reg_1619 <= ap_reg_pp0_iter4_p_Val2_s_reg_1619;
        ap_reg_pp0_iter5_snr_V_read_reg_1614 <= ap_reg_pp0_iter4_snr_V_read_reg_1614;
        ap_reg_pp0_iter5_tmp_106_1_reg_1676 <= ap_reg_pp0_iter4_tmp_106_1_reg_1676;
        ap_reg_pp0_iter5_tmp_106_2_reg_1703 <= ap_reg_pp0_iter4_tmp_106_2_reg_1703;
        ap_reg_pp0_iter5_tmp_106_3_reg_1730 <= ap_reg_pp0_iter4_tmp_106_3_reg_1730;
        ap_reg_pp0_iter5_tmp_35_reg_1854 <= ap_reg_pp0_iter4_tmp_35_reg_1854;
        ap_reg_pp0_iter5_tmp_36_reg_1834 <= ap_reg_pp0_iter4_tmp_36_reg_1834;
        ap_reg_pp0_iter5_tmp_69_reg_1649 <= ap_reg_pp0_iter4_tmp_69_reg_1649;
        ap_reg_pp0_iter6_coarseContents308_lo_2_reg_1899 <= coarseContents308_lo_2_reg_1899;
        ap_reg_pp0_iter6_coarseContents308_lo_reg_1879 <= coarseContents308_lo_reg_1879;
        ap_reg_pp0_iter6_p_Val2_s_reg_1619 <= ap_reg_pp0_iter5_p_Val2_s_reg_1619;
        ap_reg_pp0_iter6_snr_V_read_reg_1614 <= ap_reg_pp0_iter5_snr_V_read_reg_1614;
        ap_reg_pp0_iter6_tmp_106_1_reg_1676 <= ap_reg_pp0_iter5_tmp_106_1_reg_1676;
        ap_reg_pp0_iter6_tmp_106_3_reg_1730 <= ap_reg_pp0_iter5_tmp_106_3_reg_1730;
        ap_reg_pp0_iter7_coarseContents308_lo_1_reg_1919 <= coarseContents308_lo_1_reg_1919;
        ap_reg_pp0_iter7_coarseContents308_lo_2_reg_1899 <= ap_reg_pp0_iter6_coarseContents308_lo_2_reg_1899;
        ap_reg_pp0_iter7_coarseContents308_lo_reg_1879 <= ap_reg_pp0_iter6_coarseContents308_lo_reg_1879;
        ap_reg_pp0_iter7_p_Val2_s_reg_1619 <= ap_reg_pp0_iter6_p_Val2_s_reg_1619;
        ap_reg_pp0_iter7_snr_V_read_reg_1614 <= ap_reg_pp0_iter6_snr_V_read_reg_1614;
        ap_reg_pp0_iter7_tmp_106_3_reg_1730 <= ap_reg_pp0_iter6_tmp_106_3_reg_1730;
        ap_reg_pp0_iter8_coarseContents308_lo_1_reg_1919 <= ap_reg_pp0_iter7_coarseContents308_lo_1_reg_1919;
        ap_reg_pp0_iter8_coarseContents308_lo_2_reg_1899 <= ap_reg_pp0_iter7_coarseContents308_lo_2_reg_1899;
        ap_reg_pp0_iter8_coarseContents308_lo_3_reg_1959 <= coarseContents308_lo_3_reg_1959;
        ap_reg_pp0_iter8_coarseContents308_lo_reg_1879 <= ap_reg_pp0_iter7_coarseContents308_lo_reg_1879;
        ap_reg_pp0_iter8_p_Val2_s_reg_1619 <= ap_reg_pp0_iter7_p_Val2_s_reg_1619;
        ap_reg_pp0_iter8_snr_V_read_reg_1614 <= ap_reg_pp0_iter7_snr_V_read_reg_1614;
        ap_reg_pp0_iter9_coarseContents308_lo_1_reg_1919 <= ap_reg_pp0_iter8_coarseContents308_lo_1_reg_1919;
        ap_reg_pp0_iter9_coarseContents308_lo_2_reg_1899 <= ap_reg_pp0_iter8_coarseContents308_lo_2_reg_1899;
        ap_reg_pp0_iter9_coarseContents308_lo_3_reg_1959 <= ap_reg_pp0_iter8_coarseContents308_lo_3_reg_1959;
        ap_reg_pp0_iter9_coarseContents308_lo_reg_1879 <= ap_reg_pp0_iter8_coarseContents308_lo_reg_1879;
        ap_reg_pp0_iter9_p_Val2_s_reg_1619 <= ap_reg_pp0_iter8_p_Val2_s_reg_1619;
        ap_reg_pp0_iter9_snr_V_read_reg_1614 <= ap_reg_pp0_iter8_snr_V_read_reg_1614;
        centralLimitNoise_V_reg_2054 <= centralLimitNoise_V_fu_1502_p2;
        r_V_22_1_reg_1999 <= grp_fu_1602_p2;
        r_V_22_2_reg_1984 <= grp_fu_1596_p2;
        r_V_22_3_reg_2024 <= grp_fu_1608_p2;
        r_V_27_reg_2074 <= grp_fu_1514_p2;
        r_V_reg_2079 <= r_V_fu_1523_p2;
        r_V_s_reg_1979 <= grp_fu_1590_p2;
        roundedNoise_V_reg_2084 <= {{r_V_fu_1523_p2[47:27]}};
        scale_V_reg_2059 <= scaleLookup_q0;
        tmp_101_reg_2089 <= {{r_V_fu_1523_p2[47:44]}};
        tmp_114_1_reg_2014 <= tmp_114_1_fu_1391_p2;
        tmp_114_2_reg_2004 <= tmp_114_2_fu_1352_p2;
        tmp_114_3_reg_2034 <= tmp_114_3_fu_1457_p2;
        tmp_17_reg_1839 <= tmp_17_fu_1224_p2;
        tmp_19_reg_1804 <= {{bramChapter_V_load_fu_932_p3[8:5]}};
        tmp_22_reg_1989 <= tmp_22_fu_1326_p2;
        tmp_23_reg_2044 <= tmp_23_fu_1473_p2;
        tmp_29_reg_1844 <= tmp_29_fu_1228_p2;
        tmp_30_reg_1814 <= {{bramChapter_V_load_s_fu_1022_p3[8:5]}};
        tmp_32_reg_1849 <= tmp_32_fu_1232_p2;
        tmp_33_reg_1824 <= {{bramChapter_V_load_2_fu_1112_p3[8:5]}};
        tmp_35_reg_1854 <= tmp_35_fu_1236_p2;
        tmp_36_reg_1834 <= {{bramChapter_V_load_3_fu_1202_p3[8:5]}};
        tmp_reg_2029 <= tmp_fu_1424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter1_icmp3_reg_1654 <= icmp3_reg_1654;
        ap_reg_pp0_iter1_icmp6_reg_1681 <= icmp6_reg_1681;
        ap_reg_pp0_iter1_icmp9_reg_1708 <= icmp9_reg_1708;
        ap_reg_pp0_iter1_icmp_reg_1627 <= icmp_reg_1627;
        ap_reg_pp0_iter1_p_Val2_s_reg_1619 <= p_Val2_s_reg_1619;
        ap_reg_pp0_iter1_phitmp6128_i_1_reg_1671 <= phitmp6128_i_1_reg_1671;
        ap_reg_pp0_iter1_phitmp6128_i_2_reg_1698 <= phitmp6128_i_2_reg_1698;
        ap_reg_pp0_iter1_phitmp6128_i_3_reg_1725 <= phitmp6128_i_3_reg_1725;
        ap_reg_pp0_iter1_phitmp6128_i_reg_1644 <= phitmp6128_i_reg_1644;
        ap_reg_pp0_iter1_snr_V_read_reg_1614 <= snr_V_read_reg_1614;
        ap_reg_pp0_iter1_tmp_106_1_reg_1676 <= tmp_106_1_reg_1676;
        ap_reg_pp0_iter1_tmp_106_2_reg_1703 <= tmp_106_2_reg_1703;
        ap_reg_pp0_iter1_tmp_106_3_reg_1730 <= tmp_106_3_reg_1730;
        ap_reg_pp0_iter1_tmp_69_reg_1649 <= tmp_69_reg_1649;
        icmp10_reg_1783 <= icmp10_fu_837_p2;
        icmp1_reg_1735 <= icmp1_fu_756_p2;
        icmp3_reg_1654 <= icmp3_fu_396_p2;
        icmp4_reg_1751 <= icmp4_fu_783_p2;
        icmp6_reg_1681 <= icmp6_fu_478_p2;
        icmp7_reg_1767 <= icmp7_fu_810_p2;
        icmp9_reg_1708 <= icmp9_fu_560_p2;
        icmp_reg_1627 <= icmp_fu_320_p2;
        norm_V_load_3_0_1_reg_1633 <= norm_V_load_3_0_1_fu_344_p3;
        norm_V_load_3_0_2_reg_1740 <= norm_V_load_3_0_2_fu_766_p3;
        norm_V_load_3_1_1_reg_1660 <= norm_V_load_3_1_1_fu_420_p3;
        norm_V_load_3_1_2_reg_1756 <= norm_V_load_3_1_2_fu_793_p3;
        norm_V_load_3_2_1_reg_1687 <= norm_V_load_3_2_1_fu_502_p3;
        norm_V_load_3_2_2_reg_1772 <= norm_V_load_3_2_2_fu_820_p3;
        norm_V_load_3_3_1_reg_1714 <= norm_V_load_3_3_1_fu_584_p3;
        norm_V_load_3_3_2_reg_1788 <= norm_V_load_3_3_2_fu_847_p3;
        p_Val2_s_reg_1619 <= chan_real_noise_lfsr;
        phitmp6128_i_1_reg_1671 <= {{chan_real_noise_lfsr[46:42]}};
        phitmp6128_i_2_reg_1698 <= {{chan_real_noise_lfsr[78:74]}};
        phitmp6128_i_3_reg_1725 <= {{chan_real_noise_lfsr[110:106]}};
        phitmp6128_i_reg_1644 <= {{chan_real_noise_lfsr[14:10]}};
        snr_V_read_reg_1614 <= snr_V;
        tmp_106_1_reg_1676 <= {{chan_real_noise_lfsr[41:32]}};
        tmp_106_2_reg_1703 <= {{chan_real_noise_lfsr[73:64]}};
        tmp_106_3_reg_1730 <= {{chan_real_noise_lfsr[105:96]}};
        tmp_56_reg_1639 <= {{norm_V_load_3_0_1_fu_344_p3[14:11]}};
        tmp_61_reg_1746 <= {{norm_V_load_3_0_2_fu_766_p3[14:13]}};
        tmp_69_reg_1649 <= tmp_69_fu_372_p1;
        tmp_72_reg_1666 <= {{norm_V_load_3_1_1_fu_420_p3[14:11]}};
        tmp_74_reg_1762 <= {{norm_V_load_3_1_2_fu_793_p3[14:13]}};
        tmp_81_reg_1693 <= {{norm_V_load_3_2_1_fu_502_p3[14:11]}};
        tmp_83_reg_1778 <= {{norm_V_load_3_2_2_fu_820_p3[14:13]}};
        tmp_90_reg_1720 <= {{norm_V_load_3_3_1_fu_584_p3[14:11]}};
        tmp_92_reg_1794 <= {{norm_V_load_3_3_2_fu_847_p3[14:13]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter6))) begin
        coarseContents308_lo_1_reg_1919 <= coarseContents308_q2;
        gradientContents_loa_1_reg_1924 <= gradientContents_q2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter5))) begin
        coarseContents308_lo_2_reg_1899 <= coarseContents308_q1;
        coarseContents308_lo_reg_1879 <= coarseContents308_q0;
        gradientContents_loa_2_reg_1904 <= gradientContents_q1;
        gradientContents_loa_reg_1884 <= gradientContents_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter7))) begin
        coarseContents308_lo_3_reg_1959 <= coarseContents308_q3;
        gradientContents_loa_3_reg_1964 <= gradientContents_q3;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0)) | (~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter20)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_idle_pp0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_enable_reg_pp0_iter4) & (1'b0 == ap_enable_reg_pp0_iter5) & (1'b0 == ap_enable_reg_pp0_iter6) & (1'b0 == ap_enable_reg_pp0_iter7) & (1'b0 == ap_enable_reg_pp0_iter8) & (1'b0 == ap_enable_reg_pp0_iter9) & (1'b0 == ap_enable_reg_pp0_iter10) & (1'b0 == ap_enable_reg_pp0_iter11) & (1'b0 == ap_enable_reg_pp0_iter12) & (1'b0 == ap_enable_reg_pp0_iter13) & (1'b0 == ap_enable_reg_pp0_iter14) & (1'b0 == ap_enable_reg_pp0_iter15) & (1'b0 == ap_enable_reg_pp0_iter16) & (1'b0 == ap_enable_reg_pp0_iter17) & (1'b0 == ap_enable_reg_pp0_iter18) & (1'b0 == ap_enable_reg_pp0_iter19) & (1'b0 == ap_enable_reg_pp0_iter20))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_enable_reg_pp0_iter4) & (1'b0 == ap_enable_reg_pp0_iter5) & (1'b0 == ap_enable_reg_pp0_iter6) & (1'b0 == ap_enable_reg_pp0_iter7) & (1'b0 == ap_enable_reg_pp0_iter8) & (1'b0 == ap_enable_reg_pp0_iter9) & (1'b0 == ap_enable_reg_pp0_iter10) & (1'b0 == ap_enable_reg_pp0_iter11) & (1'b0 == ap_enable_reg_pp0_iter12) & (1'b0 == ap_enable_reg_pp0_iter13) & (1'b0 == ap_enable_reg_pp0_iter14) & (1'b0 == ap_enable_reg_pp0_iter15) & (1'b0 == ap_enable_reg_pp0_iter16) & (1'b0 == ap_enable_reg_pp0_iter17) & (1'b0 == ap_enable_reg_pp0_iter18) & (1'b0 == ap_enable_reg_pp0_iter19))) begin
        ap_idle_pp0_0to19 = 1'b1;
    end else begin
        ap_idle_pp0_0to19 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_idle_pp0_0to19))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter4))) begin
        coarseContents308_ce0 = 1'b1;
    end else begin
        coarseContents308_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter4))) begin
        coarseContents308_ce1 = 1'b1;
    end else begin
        coarseContents308_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter5))) begin
        coarseContents308_ce2 = 1'b1;
    end else begin
        coarseContents308_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter6))) begin
        coarseContents308_ce3 = 1'b1;
    end else begin
        coarseContents308_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter4))) begin
        gradientContents_ce0 = 1'b1;
    end else begin
        gradientContents_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter4))) begin
        gradientContents_ce1 = 1'b1;
    end else begin
        gradientContents_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter5))) begin
        gradientContents_ce2 = 1'b1;
    end else begin
        gradientContents_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter6))) begin
        gradientContents_ce3 = 1'b1;
    end else begin
        gradientContents_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (1'b1 == ap_ce))) begin
        grp_fu_1514_ce = 1'b1;
    end else begin
        grp_fu_1514_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (1'b1 == ap_ce))) begin
        grp_fu_1590_ce = 1'b1;
    end else begin
        grp_fu_1590_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (1'b1 == ap_ce))) begin
        grp_fu_1596_ce = 1'b1;
    end else begin
        grp_fu_1596_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (1'b1 == ap_ce))) begin
        grp_fu_1602_ce = 1'b1;
    end else begin
        grp_fu_1602_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (1'b1 == ap_ce))) begin
        grp_fu_1608_ce = 1'b1;
    end else begin
        grp_fu_1608_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_ce == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter12))) begin
        scaleLookup_ce0 = 1'b1;
    end else begin
        scaleLookup_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign addconv_i_1_fu_1397_p2 = ($signed(tmp_108_1_fu_1377_p1) + $signed(r_V_23_1_cast_fu_1387_p1));

assign addconv_i_2_fu_1358_p2 = ($signed(tmp_108_2_fu_1338_p1) + $signed(r_V_23_2_cast_fu_1348_p1));

assign addconv_i_3_fu_1463_p2 = ($signed(tmp_108_3_fu_1443_p1) + $signed(r_V_23_3_cast_fu_1453_p1));

assign addconv_i_fu_1332_p2 = ($signed(tmp_21_fu_1312_p1) + $signed(r_V_23_cast_fu_1322_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((tmp_28_fu_1576_p2[0:0] === 1'b1) ? saturatedNoise_V_1_fu_1568_p3 : saturatedNoise_V_fu_1559_p4);

assign bramChapter_V_load_1_10_fu_1166_p3 = ((icmp11_fu_1155_p2[0:0] === 1'b1) ? bramChapter_V_load_1_11_fu_1148_p3 : tmp_136_3_1_fu_1160_p2);

assign bramChapter_V_load_1_11_fu_1148_p3 = ((icmp10_reg_1783[0:0] === 1'b1) ? bramChapter_V_load_1_9_fu_1134_p3 : tmp_136_3_s_fu_1141_p3);

assign bramChapter_V_load_1_1_fu_878_p3 = ((icmp1_reg_1735[0:0] === 1'b1) ? bramChapter_V_load_1_fu_864_p3 : tmp_136_0_s_fu_871_p3);

assign bramChapter_V_load_1_2_fu_896_p3 = ((icmp2_fu_885_p2[0:0] === 1'b1) ? bramChapter_V_load_1_1_fu_878_p3 : tmp_136_0_1_fu_890_p2);

assign bramChapter_V_load_1_3_fu_954_p3 = ((ap_reg_pp0_iter1_icmp3_reg_1654[0:0] === 1'b1) ? 9'd0 : 9'd256);

assign bramChapter_V_load_1_4_fu_968_p3 = ((icmp4_reg_1751[0:0] === 1'b1) ? bramChapter_V_load_1_3_fu_954_p3 : tmp_136_1_s_fu_961_p3);

assign bramChapter_V_load_1_5_fu_986_p3 = ((icmp5_fu_975_p2[0:0] === 1'b1) ? bramChapter_V_load_1_4_fu_968_p3 : tmp_136_1_1_fu_980_p2);

assign bramChapter_V_load_1_6_fu_1044_p3 = ((ap_reg_pp0_iter1_icmp6_reg_1681[0:0] === 1'b1) ? 9'd0 : 9'd256);

assign bramChapter_V_load_1_7_fu_1058_p3 = ((icmp7_reg_1767[0:0] === 1'b1) ? bramChapter_V_load_1_6_fu_1044_p3 : tmp_136_2_s_fu_1051_p3);

assign bramChapter_V_load_1_8_fu_1076_p3 = ((icmp8_fu_1065_p2[0:0] === 1'b1) ? bramChapter_V_load_1_7_fu_1058_p3 : tmp_136_2_1_fu_1070_p2);

assign bramChapter_V_load_1_9_fu_1134_p3 = ((ap_reg_pp0_iter1_icmp9_reg_1708[0:0] === 1'b1) ? 9'd0 : 9'd256);

assign bramChapter_V_load_1_fu_864_p3 = ((ap_reg_pp0_iter1_icmp_reg_1627[0:0] === 1'b1) ? 9'd0 : 9'd256);

assign bramChapter_V_load_2_fu_1112_p3 = ((tmp_86_fu_1098_p3[0:0] === 1'b1) ? tmp_136_2_3_fu_1106_p2 : bramChapter_V_load_1_8_fu_1076_p3);

assign bramChapter_V_load_3_fu_1202_p3 = ((tmp_95_fu_1188_p3[0:0] === 1'b1) ? tmp_136_3_3_fu_1196_p2 : bramChapter_V_load_1_10_fu_1166_p3);

assign bramChapter_V_load_fu_932_p3 = ((tmp_67_fu_918_p3[0:0] === 1'b1) ? tmp_136_0_3_fu_926_p2 : bramChapter_V_load_1_2_fu_896_p3);

assign bramChapter_V_load_s_fu_1022_p3 = ((tmp_77_fu_1008_p3[0:0] === 1'b1) ? tmp_136_1_3_fu_1016_p2 : bramChapter_V_load_1_5_fu_986_p3);

assign centralLimitNoise_V_fu_1502_p2 = ($signed(tmp_s_fu_1495_p1) + $signed(tmp_69_cast_fu_1499_p1));

assign coarseContents308_address0 = tmp_20_fu_1246_p1;

assign coarseContents308_address1 = tmp_107_2_fu_1258_p1;

assign coarseContents308_address2 = tmp_107_1_fu_1270_p1;

assign coarseContents308_address3 = tmp_107_3_fu_1294_p1;

assign gradientContents_address0 = tmp_20_fu_1246_p1;

assign gradientContents_address1 = tmp_107_2_fu_1258_p1;

assign gradientContents_address2 = tmp_107_1_fu_1270_p1;

assign gradientContents_address3 = tmp_107_3_fu_1294_p1;

assign grp_fu_1514_p0 = grp_fu_1514_p00;

assign grp_fu_1514_p00 = scale_V_reg_2059;

assign grp_fu_1590_p1 = grp_fu_1590_p10;

assign grp_fu_1590_p10 = gradientContents_loa_reg_1884;

assign grp_fu_1596_p1 = grp_fu_1596_p10;

assign grp_fu_1596_p10 = gradientContents_loa_2_reg_1904;

assign grp_fu_1602_p1 = grp_fu_1602_p10;

assign grp_fu_1602_p10 = gradientContents_loa_1_reg_1924;

assign grp_fu_1608_p1 = grp_fu_1608_p10;

assign grp_fu_1608_p10 = gradientContents_loa_3_reg_1964;

assign icmp10_fu_837_p2 = ((tmp_90_reg_1720 == 4'd0) ? 1'b1 : 1'b0);

assign icmp11_fu_1155_p2 = ((tmp_92_reg_1794 == 2'd0) ? 1'b1 : 1'b0);

assign icmp12_fu_1549_p2 = (($signed(tmp_101_reg_2089) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp1_fu_756_p2 = ((tmp_56_reg_1639 == 4'd0) ? 1'b1 : 1'b0);

assign icmp2_fu_885_p2 = ((tmp_61_reg_1746 == 2'd0) ? 1'b1 : 1'b0);

assign icmp3_fu_396_p2 = ((tmp_71_fu_386_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp4_fu_783_p2 = ((tmp_72_reg_1666 == 4'd0) ? 1'b1 : 1'b0);

assign icmp5_fu_975_p2 = ((tmp_74_reg_1762 == 2'd0) ? 1'b1 : 1'b0);

assign icmp6_fu_478_p2 = ((tmp_80_fu_468_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp7_fu_810_p2 = ((tmp_81_reg_1693 == 4'd0) ? 1'b1 : 1'b0);

assign icmp8_fu_1065_p2 = ((tmp_83_reg_1778 == 2'd0) ? 1'b1 : 1'b0);

assign icmp9_fu_560_p2 = ((tmp_89_fu_550_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_fu_320_p2 = ((tmp_55_fu_310_p4 == 8'd0) ? 1'b1 : 1'b0);

assign noiseGen_V_load_1_fu_1437_p3 = ((tmp_70_fu_1430_p3[0:0] === 1'b1) ? tmp_114_1_reg_2014 : addconv_i_1_reg_2019);

assign noiseGen_V_load_2_fu_1410_p3 = ((tmp_79_fu_1403_p3[0:0] === 1'b1) ? tmp_114_2_reg_2004 : addconv_i_2_reg_2009);

assign noiseGen_V_load_3_fu_1489_p3 = ((tmp_88_fu_1482_p3[0:0] === 1'b1) ? tmp_114_3_reg_2034 : addconv_i_3_reg_2039);

assign noiseGen_V_load_fu_1371_p3 = ((tmp_54_fu_1364_p3[0:0] === 1'b1) ? tmp_22_reg_1989 : addconv_i_reg_1994);

assign norm_V_load_3_0_1_fu_344_p3 = ((icmp_fu_320_p2[0:0] === 1'b1) ? tmp_16_fu_336_p3 : phitmp6131_i_fu_300_p4);

assign norm_V_load_3_0_2_fu_766_p3 = ((icmp1_fu_756_p2[0:0] === 1'b1) ? tmp_60_fu_761_p2 : norm_V_load_3_0_1_reg_1633);

assign norm_V_load_3_1_1_fu_420_p3 = ((icmp3_fu_396_p2[0:0] === 1'b1) ? tmp_134_1_fu_412_p3 : phitmp6131_i_1_fu_376_p4);

assign norm_V_load_3_1_2_fu_793_p3 = ((icmp4_fu_783_p2[0:0] === 1'b1) ? tmp_73_fu_788_p2 : norm_V_load_3_1_1_reg_1660);

assign norm_V_load_3_2_1_fu_502_p3 = ((icmp6_fu_478_p2[0:0] === 1'b1) ? tmp_134_2_fu_494_p3 : phitmp6131_i_2_fu_458_p4);

assign norm_V_load_3_2_2_fu_820_p3 = ((icmp7_fu_810_p2[0:0] === 1'b1) ? tmp_82_fu_815_p2 : norm_V_load_3_2_1_reg_1687);

assign norm_V_load_3_3_1_fu_584_p3 = ((icmp9_fu_560_p2[0:0] === 1'b1) ? tmp_134_3_fu_576_p3 : phitmp6131_i_3_fu_540_p4);

assign norm_V_load_3_3_2_fu_847_p3 = ((icmp10_fu_837_p2[0:0] === 1'b1) ? tmp_91_fu_842_p2 : norm_V_load_3_3_1_reg_1714);

assign p_0202_0_i_cast_fu_1416_p1 = $signed(noiseGen_V_load_fu_1371_p3);

assign p_0210_0_i_cast_fu_1469_p1 = $signed(noiseGen_V_load_1_fu_1437_p3);

assign p_Result_s_fu_742_p3 = {{r_V_20_fu_686_p2}, {r_V_26_fu_736_p2}};

assign phitmp6131_i_1_fu_376_p4 = {{chan_real_noise_lfsr[61:47]}};

assign phitmp6131_i_2_fu_458_p4 = {{chan_real_noise_lfsr[93:79]}};

assign phitmp6131_i_3_fu_540_p4 = {{chan_real_noise_lfsr[125:111]}};

assign phitmp6131_i_fu_300_p4 = {{chan_real_noise_lfsr[29:15]}};

assign r_V_10_fu_710_p4 = {{r_V_22_fu_704_p2[63:13]}};

assign r_V_15_fu_646_p3 = {{tmp_37_fu_636_p4}, {34'd0}};

assign r_V_16_fu_654_p2 = (r_V_15_fu_646_p3 ^ rhs_V_fu_622_p4);

assign r_V_17_fu_670_p1 = r_V_4_fu_660_p4;

assign r_V_18_fu_674_p2 = (r_V_17_fu_670_p1 ^ r_V_16_fu_654_p2);

assign r_V_19_fu_680_p2 = r_V_18_fu_674_p2 << 64'd1;

assign r_V_1_fu_1315_p3 = {{ap_reg_pp0_iter9_coarseContents308_lo_reg_1879}, {10'd0}};

assign r_V_20_fu_686_p2 = (r_V_19_fu_680_p2 ^ r_V_18_fu_674_p2);

assign r_V_21_fu_696_p3 = {{tmp_99_fu_692_p1}, {58'd0}};

assign r_V_22_fu_704_p2 = (r_V_21_fu_696_p3 ^ rhs_V_3_fu_632_p1);

assign r_V_23_1_cast_fu_1387_p1 = r_V_23_1_fu_1380_p3;

assign r_V_23_1_fu_1380_p3 = {{ap_reg_pp0_iter10_coarseContents308_lo_1_reg_1919}, {10'd0}};

assign r_V_23_2_cast_fu_1348_p1 = r_V_23_2_fu_1341_p3;

assign r_V_23_2_fu_1341_p3 = {{ap_reg_pp0_iter9_coarseContents308_lo_2_reg_1899}, {10'd0}};

assign r_V_23_3_cast_fu_1453_p1 = r_V_23_3_fu_1446_p3;

assign r_V_23_3_fu_1446_p3 = {{ap_reg_pp0_iter11_coarseContents308_lo_3_reg_1959}, {10'd0}};

assign r_V_23_cast_fu_1322_p1 = r_V_1_fu_1315_p3;

assign r_V_23_fu_720_p1 = r_V_10_fu_710_p4;

assign r_V_24_fu_724_p2 = (r_V_23_fu_720_p1 ^ r_V_22_fu_704_p2);

assign r_V_25_fu_730_p2 = r_V_24_fu_724_p2 << 64'd7;

assign r_V_26_fu_736_p2 = (r_V_25_fu_730_p2 ^ r_V_24_fu_724_p2);

assign r_V_4_fu_660_p4 = {{r_V_16_fu_654_p2[63:35]}};

assign r_V_fu_1523_p2 = (49'd67108864 + tmp_25_fu_1520_p1);

assign rhs_V_3_fu_632_p1 = chan_real_noise_lfsr[63:0];

assign rhs_V_fu_622_p4 = {{chan_real_noise_lfsr[127:64]}};

assign saturatedNoise_V_1_fu_1568_p3 = ((icmp12_fu_1549_p2[0:0] === 1'b1) ? 18'd131071 : 18'd131073);

assign saturatedNoise_V_fu_1559_p4 = {{r_V_reg_2079[44:27]}};

assign scaleLookup_address0 = tmp_24_fu_1478_p1;

assign tmp_105_1_fu_1264_p3 = {{ap_reg_pp0_iter4_tmp_30_reg_1814}, {ap_reg_pp0_iter4_tmp_29_reg_1844}};

assign tmp_105_2_fu_1252_p3 = {{ap_reg_pp0_iter3_tmp_33_reg_1824}, {tmp_32_reg_1849}};

assign tmp_105_3_fu_1288_p3 = {{ap_reg_pp0_iter5_tmp_36_reg_1834}, {ap_reg_pp0_iter5_tmp_35_reg_1854}};

assign tmp_107_1_fu_1270_p1 = tmp_105_1_fu_1264_p3;

assign tmp_107_2_fu_1258_p1 = tmp_105_2_fu_1252_p3;

assign tmp_107_3_fu_1294_p1 = tmp_105_3_fu_1288_p3;

assign tmp_108_1_fu_1377_p1 = r_V_22_1_reg_1999;

assign tmp_108_2_fu_1338_p1 = r_V_22_2_reg_1984;

assign tmp_108_3_fu_1443_p1 = r_V_22_3_reg_2024;

assign tmp_114_1_fu_1391_p2 = ($signed(tmp_108_1_fu_1377_p1) - $signed(r_V_23_1_cast_fu_1387_p1));

assign tmp_114_2_fu_1352_p2 = ($signed(tmp_108_2_fu_1338_p1) - $signed(r_V_23_2_cast_fu_1348_p1));

assign tmp_114_3_fu_1457_p2 = ($signed(tmp_108_3_fu_1443_p1) - $signed(r_V_23_3_cast_fu_1453_p1));

assign tmp_134_1_fu_412_p3 = {{tmp_26_fu_402_p4}, {8'd0}};

assign tmp_134_2_fu_494_p3 = {{tmp_31_fu_484_p4}, {8'd0}};

assign tmp_134_3_fu_576_p3 = {{tmp_34_fu_566_p4}, {8'd0}};

assign tmp_136_0_1_fu_890_p2 = (bramChapter_V_load_1_1_fu_878_p3 | 9'd64);

assign tmp_136_0_3_fu_926_p2 = (bramChapter_V_load_1_2_fu_896_p3 | 9'd32);

assign tmp_136_0_s_fu_871_p3 = ((ap_reg_pp0_iter1_icmp_reg_1627[0:0] === 1'b1) ? 9'd128 : 9'd384);

assign tmp_136_1_1_fu_980_p2 = (bramChapter_V_load_1_4_fu_968_p3 | 9'd64);

assign tmp_136_1_3_fu_1016_p2 = (bramChapter_V_load_1_5_fu_986_p3 | 9'd32);

assign tmp_136_1_s_fu_961_p3 = ((ap_reg_pp0_iter1_icmp3_reg_1654[0:0] === 1'b1) ? 9'd128 : 9'd384);

assign tmp_136_2_1_fu_1070_p2 = (bramChapter_V_load_1_7_fu_1058_p3 | 9'd64);

assign tmp_136_2_3_fu_1106_p2 = (bramChapter_V_load_1_8_fu_1076_p3 | 9'd32);

assign tmp_136_2_s_fu_1051_p3 = ((ap_reg_pp0_iter1_icmp6_reg_1681[0:0] === 1'b1) ? 9'd128 : 9'd384);

assign tmp_136_3_1_fu_1160_p2 = (bramChapter_V_load_1_11_fu_1148_p3 | 9'd64);

assign tmp_136_3_3_fu_1196_p2 = (bramChapter_V_load_1_10_fu_1166_p3 | 9'd32);

assign tmp_136_3_s_fu_1141_p3 = ((ap_reg_pp0_iter1_icmp9_reg_1708[0:0] === 1'b1) ? 9'd128 : 9'd384);

assign tmp_15_fu_326_p4 = {{chan_real_noise_lfsr[21:15]}};

assign tmp_16_fu_336_p3 = {{tmp_15_fu_326_p4}, {8'd0}};

assign tmp_17_fu_1224_p2 = (tmp_68_reg_1799 | ap_reg_pp0_iter2_phitmp6128_i_reg_1644);

assign tmp_18_fu_1240_p3 = {{ap_reg_pp0_iter3_tmp_19_reg_1804}, {tmp_17_reg_1839}};

assign tmp_20_fu_1246_p1 = tmp_18_fu_1240_p3;

assign tmp_21_fu_1312_p1 = r_V_s_reg_1979;

assign tmp_22_fu_1326_p2 = ($signed(tmp_21_fu_1312_p1) - $signed(r_V_23_cast_fu_1322_p1));

assign tmp_23_fu_1473_p2 = ($signed(p_0210_0_i_cast_fu_1469_p1) + $signed(tmp_reg_2029));

assign tmp_24_fu_1478_p1 = ap_reg_pp0_iter11_snr_V_read_reg_1614;

assign tmp_25_fu_1520_p1 = r_V_27_reg_2074;

assign tmp_26_fu_402_p4 = {{chan_real_noise_lfsr[53:47]}};

assign tmp_27_fu_1554_p2 = (($signed(roundedNoise_V_reg_2084) < $signed(21'd1966081)) ? 1'b1 : 1'b0);

assign tmp_28_fu_1576_p2 = (icmp12_fu_1549_p2 | tmp_27_fu_1554_p2);

assign tmp_29_fu_1228_p2 = (tmp_78_reg_1809 | ap_reg_pp0_iter2_phitmp6128_i_1_reg_1671);

assign tmp_31_fu_484_p4 = {{chan_real_noise_lfsr[85:79]}};

assign tmp_32_fu_1232_p2 = (tmp_87_reg_1819 | ap_reg_pp0_iter2_phitmp6128_i_2_reg_1698);

assign tmp_34_fu_566_p4 = {{chan_real_noise_lfsr[117:111]}};

assign tmp_35_fu_1236_p2 = (tmp_96_reg_1829 | ap_reg_pp0_iter2_phitmp6128_i_3_reg_1725);

assign tmp_37_fu_636_p4 = {{chan_real_noise_lfsr[93:64]}};

assign tmp_54_fu_1364_p3 = ap_reg_pp0_iter10_p_Val2_s_reg_1619[32'd31];

assign tmp_55_fu_310_p4 = {{chan_real_noise_lfsr[29:22]}};

assign tmp_60_fu_761_p2 = norm_V_load_3_0_1_reg_1633 << 15'd4;

assign tmp_62_fu_904_p3 = norm_V_load_3_0_2_reg_1740[32'd12];

assign tmp_66_fu_911_p3 = norm_V_load_3_0_2_reg_1740[32'd14];

assign tmp_67_fu_918_p3 = ((icmp2_fu_885_p2[0:0] === 1'b1) ? tmp_62_fu_904_p3 : tmp_66_fu_911_p3);

assign tmp_68_fu_940_p1 = bramChapter_V_load_fu_932_p3[4:0];

assign tmp_69_cast_fu_1499_p1 = $signed(tmp_23_reg_2044);

assign tmp_69_fu_372_p1 = chan_real_noise_lfsr[9:0];

assign tmp_70_fu_1430_p3 = ap_reg_pp0_iter11_p_Val2_s_reg_1619[32'd63];

assign tmp_71_fu_386_p4 = {{chan_real_noise_lfsr[61:54]}};

assign tmp_73_fu_788_p2 = norm_V_load_3_1_1_reg_1660 << 15'd4;

assign tmp_75_fu_994_p3 = norm_V_load_3_1_2_reg_1756[32'd12];

assign tmp_76_fu_1001_p3 = norm_V_load_3_1_2_reg_1756[32'd14];

assign tmp_77_fu_1008_p3 = ((icmp5_fu_975_p2[0:0] === 1'b1) ? tmp_75_fu_994_p3 : tmp_76_fu_1001_p3);

assign tmp_78_fu_1030_p1 = bramChapter_V_load_s_fu_1022_p3[4:0];

assign tmp_79_fu_1403_p3 = ap_reg_pp0_iter10_p_Val2_s_reg_1619[32'd95];

assign tmp_80_fu_468_p4 = {{chan_real_noise_lfsr[93:86]}};

assign tmp_82_fu_815_p2 = norm_V_load_3_2_1_reg_1687 << 15'd4;

assign tmp_84_fu_1084_p3 = norm_V_load_3_2_2_reg_1772[32'd12];

assign tmp_85_fu_1091_p3 = norm_V_load_3_2_2_reg_1772[32'd14];

assign tmp_86_fu_1098_p3 = ((icmp8_fu_1065_p2[0:0] === 1'b1) ? tmp_84_fu_1084_p3 : tmp_85_fu_1091_p3);

assign tmp_87_fu_1120_p1 = bramChapter_V_load_2_fu_1112_p3[4:0];

assign tmp_88_fu_1482_p3 = ap_reg_pp0_iter12_p_Val2_s_reg_1619[32'd127];

assign tmp_89_fu_550_p4 = {{chan_real_noise_lfsr[125:118]}};

assign tmp_91_fu_842_p2 = norm_V_load_3_3_1_reg_1714 << 15'd4;

assign tmp_93_fu_1174_p3 = norm_V_load_3_3_2_reg_1788[32'd12];

assign tmp_94_fu_1181_p3 = norm_V_load_3_3_2_reg_1788[32'd14];

assign tmp_95_fu_1188_p3 = ((icmp11_fu_1155_p2[0:0] === 1'b1) ? tmp_93_fu_1174_p3 : tmp_94_fu_1181_p3);

assign tmp_96_fu_1210_p1 = bramChapter_V_load_3_fu_1202_p3[4:0];

assign tmp_99_fu_692_p1 = chan_real_noise_lfsr[5:0];

assign tmp_cast_fu_1420_p1 = $signed(noiseGen_V_load_2_fu_1410_p3);

assign tmp_fu_1424_p2 = ($signed(tmp_cast_fu_1420_p1) + $signed(p_0202_0_i_cast_fu_1416_p1));

assign tmp_s_fu_1495_p1 = $signed(noiseGen_V_load_3_fu_1489_p3);

always @ (posedge ap_clk) begin
    tmp_68_reg_1799[4:0] <= 5'b00000;
    tmp_78_reg_1809[4:0] <= 5'b00000;
    tmp_87_reg_1819[4:0] <= 5'b00000;
    tmp_96_reg_1829[4:0] <= 5'b00000;
end

endmodule //awgn_real
