// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module compress_soft (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        n_dout,
        n_empty_n,
        n_read,
        fec_type_dout,
        fec_type_empty_n,
        fec_type_read,
        soft_words_tx_dout,
        soft_words_tx_empty_n,
        soft_words_tx_read,
        soft_words_TDATA,
        soft_words_TVALID,
        soft_words_TREADY,
        soft_words_TLAST,
        soft_data_i_V_V_dout,
        soft_data_i_V_V_empty_n,
        soft_data_i_V_V_read,
        soft_data_TDATA,
        soft_data_TVALID,
        soft_data_TREADY,
        soft_data_TLAST
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_pp0_stage0 = 7'd8;
parameter    ap_ST_fsm_state12 = 7'd16;
parameter    ap_ST_fsm_state13 = 7'd32;
parameter    ap_ST_fsm_state14 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] n_dout;
input   n_empty_n;
output   n_read;
input  [31:0] fec_type_dout;
input   fec_type_empty_n;
output   fec_type_read;
input  [31:0] soft_words_tx_dout;
input   soft_words_tx_empty_n;
output   soft_words_tx_read;
output  [7:0] soft_words_TDATA;
output   soft_words_TVALID;
input   soft_words_TREADY;
output  [0:0] soft_words_TLAST;
input  [15:0] soft_data_i_V_V_dout;
input   soft_data_i_V_V_empty_n;
output   soft_data_i_V_V_read;
output  [127:0] soft_data_TDATA;
output   soft_data_TVALID;
input   soft_data_TREADY;
output  [0:0] soft_data_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg n_read;
reg fec_type_read;
reg soft_words_tx_read;
reg soft_words_TVALID;
reg[0:0] soft_words_TLAST;
reg soft_data_i_V_V_read;
reg[127:0] soft_data_TDATA;
reg soft_data_TVALID;
reg[0:0] soft_data_TLAST;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    n_blk_n;
reg    fec_type_blk_n;
reg    soft_words_tx_blk_n;
reg    soft_words_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_i_fu_289_p2;
reg    ap_enable_reg_pp0_iter7;
reg   [0:0] tmp_47_i_reg_934;
reg   [0:0] ap_reg_pp0_iter6_tmp_47_i_reg_934;
reg   [0:0] tmp_29_i_reg_909;
reg   [0:0] tmp_last_V_reg_943;
reg   [0:0] ap_reg_pp0_iter6_tmp_last_V_reg_943;
wire    ap_CS_fsm_state14;
reg   [0:0] tmp_30_i_reg_1132;
wire   [0:0] tmp_32_i_fu_871_p2;
reg    soft_data_i_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] exitcond_i_reg_924;
reg    soft_data_TDATA_blk_n;
reg   [127:0] p_Val2_9_reg_242;
reg   [31:0] i_i_reg_254;
reg   [31:0] n_read_reg_876;
reg    ap_block_state1;
reg   [31:0] fec_type_read_reg_882;
reg   [31:0] soft_words_tx_read_reg_887;
wire   [0:0] tmp_i_74_fu_294_p2;
reg   [0:0] tmp_i_74_reg_903;
reg    ap_sig_ioackin_soft_words_TREADY;
reg    ap_block_state2_io;
wire   [0:0] tmp_29_i_fu_299_p2;
wire   [0:0] sel_tmp1_fu_304_p2;
reg   [0:0] sel_tmp1_reg_913;
wire    ap_CS_fsm_state3;
reg   [15:0] s_i_2_load_reg_918;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_state5;
reg    ap_sig_ioackin_soft_data_TREADY;
reg    ap_predicate_op143_write_state11;
reg    ap_predicate_op145_write_state11;
reg    ap_block_state11_io;
wire   [0:0] exitcond_i_fu_312_p2;
reg   [0:0] ap_reg_pp0_iter1_exitcond_i_reg_924;
reg   [0:0] ap_reg_pp0_iter2_exitcond_i_reg_924;
reg   [0:0] ap_reg_pp0_iter3_exitcond_i_reg_924;
reg   [0:0] ap_reg_pp0_iter4_exitcond_i_reg_924;
reg   [0:0] ap_reg_pp0_iter5_exitcond_i_reg_924;
reg   [0:0] ap_reg_pp0_iter6_exitcond_i_reg_924;
wire   [31:0] i_fu_317_p2;
reg   [31:0] i_reg_928;
wire   [0:0] tmp_47_i_fu_323_p2;
reg   [0:0] ap_reg_pp0_iter1_tmp_47_i_reg_934;
reg   [0:0] ap_reg_pp0_iter2_tmp_47_i_reg_934;
reg   [0:0] ap_reg_pp0_iter3_tmp_47_i_reg_934;
reg   [0:0] ap_reg_pp0_iter4_tmp_47_i_reg_934;
reg   [0:0] ap_reg_pp0_iter5_tmp_47_i_reg_934;
reg   [15:0] tmp_V_reg_938;
wire   [0:0] tmp_last_V_fu_340_p2;
reg   [0:0] ap_reg_pp0_iter2_tmp_last_V_reg_943;
reg   [0:0] ap_reg_pp0_iter3_tmp_last_V_reg_943;
reg   [0:0] ap_reg_pp0_iter4_tmp_last_V_reg_943;
reg   [0:0] ap_reg_pp0_iter5_tmp_last_V_reg_943;
wire   [15:0] soft_src_V_fu_344_p2;
reg   [15:0] soft_src_V_reg_948;
reg   [15:0] ap_reg_pp0_iter3_soft_src_V_reg_948;
reg   [15:0] ap_reg_pp0_iter4_soft_src_V_reg_948;
reg   [0:0] signbit_reg_957;
reg   [0:0] ap_reg_pp0_iter3_signbit_reg_957;
reg   [0:0] ap_reg_pp0_iter4_signbit_reg_957;
reg   [0:0] ap_reg_pp0_iter5_signbit_reg_957;
reg   [5:0] p_Val2_2_reg_964;
reg   [5:0] ap_reg_pp0_iter3_p_Val2_2_reg_964;
wire   [2:0] tmp_15_fu_367_p1;
reg   [2:0] tmp_15_reg_969;
reg   [7:0] p_Val2_3_reg_974;
reg   [7:0] ap_reg_pp0_iter3_p_Val2_3_reg_974;
reg   [4:0] p_Result_10_i_reg_979;
reg   [5:0] p_Result_11_i_reg_984;
reg   [2:0] p_Result_15_i_reg_990;
reg   [3:0] p_Result_16_i_reg_995;
wire   [0:0] r_fu_421_p2;
reg   [0:0] r_reg_1001;
wire   [0:0] not_s_i_i_i_fu_426_p2;
reg   [0:0] not_s_i_i_i_reg_1006;
reg   [0:0] ap_reg_pp0_iter4_not_s_i_i_i_reg_1006;
wire   [0:0] Range2_all_ones_fu_431_p2;
reg   [0:0] Range2_all_ones_reg_1013;
reg   [0:0] ap_reg_pp0_iter4_Range2_all_ones_reg_1013;
wire   [0:0] Range1_all_ones_fu_436_p2;
reg   [0:0] Range1_all_ones_reg_1018;
reg   [0:0] ap_reg_pp0_iter4_Range1_all_ones_reg_1018;
reg   [0:0] ap_reg_pp0_iter5_Range1_all_ones_reg_1018;
wire   [0:0] Range1_all_zeros_fu_441_p2;
reg   [0:0] Range1_all_zeros_reg_1025;
reg   [0:0] ap_reg_pp0_iter4_Range1_all_zeros_reg_1025;
wire   [0:0] Range2_all_ones_1_fu_446_p2;
reg   [0:0] Range2_all_ones_1_reg_1030;
reg   [0:0] ap_reg_pp0_iter4_Range2_all_ones_1_reg_1030;
wire   [0:0] Range1_all_ones_1_fu_451_p2;
reg   [0:0] Range1_all_ones_1_reg_1035;
reg   [0:0] ap_reg_pp0_iter4_Range1_all_ones_1_reg_1035;
reg   [0:0] ap_reg_pp0_iter5_Range1_all_ones_1_reg_1035;
wire   [0:0] Range1_all_zeros_1_fu_456_p2;
reg   [0:0] Range1_all_zeros_1_reg_1042;
reg   [0:0] ap_reg_pp0_iter4_Range1_all_zeros_1_reg_1042;
wire   [5:0] p_Val2_5_fu_482_p2;
reg   [5:0] p_Val2_5_reg_1047;
reg   [5:0] ap_reg_pp0_iter5_p_Val2_5_reg_1047;
wire   [7:0] p_Val2_6_fu_491_p2;
reg   [7:0] p_Val2_6_reg_1053;
reg   [7:0] ap_reg_pp0_iter5_p_Val2_6_reg_1053;
reg   [7:0] ap_reg_pp0_iter6_p_Val2_6_reg_1053;
reg   [0:0] newsignbit_reg_1059;
reg   [0:0] newsignbit_2_reg_1066;
wire   [4:0] tmp_22_fu_512_p1;
reg   [4:0] tmp_22_reg_1073;
wire   [6:0] tmp_23_fu_516_p1;
reg   [6:0] tmp_23_reg_1078;
wire   [0:0] carry_fu_539_p2;
reg   [0:0] carry_reg_1083;
wire   [0:0] carry_1_fu_563_p2;
reg   [0:0] carry_1_reg_1088;
wire   [0:0] overflow_fu_629_p2;
reg   [0:0] overflow_reg_1093;
wire   [0:0] overflow_1_fu_656_p2;
reg   [0:0] overflow_1_reg_1099;
reg   [0:0] ap_reg_pp0_iter6_overflow_1_reg_1099;
wire   [0:0] tmp_43_i4_fu_677_p2;
reg   [0:0] tmp_43_i4_reg_1105;
wire   [0:0] tmp_45_i5_fu_688_p2;
reg   [0:0] tmp_45_i5_reg_1110;
wire   [0:0] underflow_1_fu_752_p2;
reg   [0:0] underflow_1_reg_1115;
wire   [5:0] ldpc_soft_V_fu_764_p3;
reg   [5:0] ldpc_soft_V_reg_1122;
wire   [127:0] data_out_V_fu_832_p3;
wire   [0:0] tmp_30_i_fu_841_p2;
wire    ap_CS_fsm_state12;
wire   [15:0] s_i_fu_846_p2;
reg   [15:0] s_i_reg_1136;
wire    ap_CS_fsm_state13;
wire   [127:0] data_out_V_1_fu_862_p3;
reg    ap_predicate_op160_write_state14;
reg    ap_predicate_op162_write_state14;
reg    ap_block_state14_io;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg   [31:0] i_i_phi_fu_258_p4;
reg   [15:0] s_i_2_i_reg_265;
reg   [127:0] p_Val2_4_reg_274;
reg   [15:0] s_i_2_fu_190;
wire   [15:0] s_i_1_fu_329_p2;
reg    ap_reg_ioackin_soft_words_TREADY;
reg    ap_reg_ioackin_soft_data_TREADY;
wire   [0:0] r_i_i_i_fu_468_p2;
wire   [0:0] qbit_fu_461_p3;
wire   [0:0] qb_assign_1_fu_472_p2;
wire   [5:0] tmp_33_i_fu_478_p1;
wire   [7:0] tmp_35_i_fu_487_p1;
wire   [0:0] tmp_16_fu_520_p3;
wire   [0:0] tmp_36_i_fu_534_p2;
wire   [0:0] tmp_17_fu_527_p3;
wire   [0:0] tmp_37_i_fu_558_p2;
wire   [0:0] tmp_19_fu_545_p3;
wire   [0:0] tmp_38_i_fu_582_p2;
wire   [0:0] p_41_i_i_fu_588_p2;
wire   [0:0] tmp_21_fu_569_p3;
wire   [0:0] tmp_39_i_fu_600_p2;
wire   [0:0] p_41_i1_i_fu_606_p2;
wire   [0:0] deleted_zeros_fu_552_p3;
wire   [0:0] p_not_i_i_fu_618_p2;
wire   [0:0] brmerge_i_i_fu_624_p2;
wire   [0:0] deleted_ones_fu_593_p3;
wire   [0:0] brmerge40_demorgan_i_fu_634_p2;
wire   [0:0] deleted_zeros_1_fu_576_p3;
wire   [0:0] p_not_i1_i_fu_645_p2;
wire   [0:0] brmerge_i1_i_fu_651_p2;
wire   [0:0] deleted_ones_1_fu_611_p3;
wire   [0:0] brmerge40_demorgan_i_1_fu_661_p2;
wire   [0:0] tmp_42_i_fu_672_p2;
wire   [0:0] brmerge40_i_i_fu_639_p2;
wire   [0:0] tmp_44_i_fu_683_p2;
wire   [0:0] brmerge40_i1_i_fu_666_p2;
wire   [0:0] p_38_i_i_fu_694_p2;
wire   [0:0] p_38_i1_i_fu_704_p2;
wire   [0:0] tmp_40_i_fu_698_p2;
wire   [0:0] tmp_fu_714_p2;
wire   [0:0] underflow_fu_719_p2;
wire   [0:0] underflow_4_not_i_fu_729_p2;
wire   [0:0] brmerge_i_i_i_fu_724_p2;
wire   [0:0] tmp_41_i_fu_708_p2;
wire   [0:0] tmp6_fu_747_p2;
wire   [0:0] brmerge_i_fu_735_p2;
wire   [5:0] p_Val2_3_mux_i_fu_740_p3;
wire   [5:0] p_Val2_3_i_fu_757_p3;
wire   [0:0] underflow_5_not_i_fu_776_p2;
wire   [0:0] brmerge_i_i1_i_fu_772_p2;
wire  signed [7:0] ldpc_soft_ext_V_fu_799_p1;
wire   [7:0] p_Val2_5_i_fu_793_p3;
wire   [0:0] brmerge2_i_fu_781_p2;
wire   [0:0] sel_tmp2_fu_809_p2;
wire   [7:0] p_Val2_5_mux_i_fu_786_p3;
wire   [7:0] sel_tmp_fu_802_p3;
wire   [7:0] p_Repl2_s_fu_814_p3;
wire   [119:0] p_Result_19_i_fu_822_p4;
wire   [119:0] p_Result_i_fu_852_p4;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_reg_ioackin_soft_words_TREADY = 1'b0;
#0 ap_reg_ioackin_soft_data_TREADY = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state14) & (ap_block_state14_io == 1'b0) & ((1'd1 == tmp_32_i_fu_871_p2) | (1'd1 == tmp_30_i_reg_1132)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == exitcond_i_fu_312_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & ~(1'd1 == exitcond_i_fu_312_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == exitcond_i_fu_312_p2)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_soft_data_TREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op160_write_state14) & (ap_block_state14_io == 1'b0)))) begin
            ap_reg_ioackin_soft_data_TREADY <= 1'b0;
        end else if ((((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) & (1'b1 == soft_data_TREADY)) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op160_write_state14) & (1'b1 == soft_data_TREADY)))) begin
            ap_reg_ioackin_soft_data_TREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_soft_words_TREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state2) & (tmp_i_fu_289_p2 == 1'd1) & (ap_block_state2_io == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op143_write_state11) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op145_write_state11) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op162_write_state14) & (ap_block_state14_io == 1'b0)))) begin
            ap_reg_ioackin_soft_words_TREADY <= 1'b0;
        end else if ((((1'b1 == ap_CS_fsm_state2) & (tmp_i_fu_289_p2 == 1'd1) & (1'b1 == soft_words_TREADY)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op143_write_state11) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) & (1'b1 == soft_words_TREADY)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op145_write_state11) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) & (1'b1 == soft_words_TREADY)) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op162_write_state14) & (1'b1 == soft_words_TREADY)))) begin
            ap_reg_ioackin_soft_words_TREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond_i_reg_924) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))))) begin
        i_i_reg_254 <= i_reg_928;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_i_reg_254 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'd0 == tmp_30_i_fu_841_p2))) begin
        p_Val2_4_reg_274 <= p_Val2_9_reg_242;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'd0 == tmp_30_i_reg_1132) & (ap_block_state14_io == 1'b0) & (1'd0 == tmp_32_i_fu_871_p2))) begin
        p_Val2_4_reg_274 <= data_out_V_1_fu_862_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter7) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter6_exitcond_i_reg_924))) begin
        p_Val2_9_reg_242 <= data_out_V_fu_832_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Val2_9_reg_242 <= 128'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == exitcond_i_fu_312_p2) & (1'd0 == tmp_47_i_fu_323_p2))) begin
        s_i_2_fu_190 <= s_i_1_fu_329_p2;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (ap_block_state2_io == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == exitcond_i_fu_312_p2) & (1'd1 == tmp_47_i_fu_323_p2)))) begin
        s_i_2_fu_190 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'd0 == tmp_30_i_fu_841_p2))) begin
        s_i_2_i_reg_265 <= s_i_2_load_reg_918;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'd0 == tmp_30_i_reg_1132) & (ap_block_state14_io == 1'b0) & (1'd0 == tmp_32_i_fu_871_p2))) begin
        s_i_2_i_reg_265 <= s_i_reg_1136;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter2_exitcond_i_reg_924))) begin
        Range1_all_ones_1_reg_1035 <= Range1_all_ones_1_fu_451_p2;
        Range1_all_zeros_1_reg_1042 <= Range1_all_zeros_1_fu_456_p2;
        Range2_all_ones_1_reg_1030 <= Range2_all_ones_1_fu_446_p2;
        not_s_i_i_i_reg_1006 <= not_s_i_i_i_fu_426_p2;
        r_reg_1001 <= r_fu_421_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == tmp_i_74_reg_903) & (1'd0 == ap_reg_pp0_iter2_exitcond_i_reg_924))) begin
        Range1_all_ones_reg_1018 <= Range1_all_ones_fu_436_p2;
        Range1_all_zeros_reg_1025 <= Range1_all_zeros_fu_441_p2;
        Range2_all_ones_reg_1013 <= Range2_all_ones_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))))) begin
        ap_reg_pp0_iter1_exitcond_i_reg_924 <= exitcond_i_reg_924;
        ap_reg_pp0_iter1_tmp_47_i_reg_934 <= tmp_47_i_reg_934;
        exitcond_i_reg_924 <= exitcond_i_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io)))) begin
        ap_reg_pp0_iter2_exitcond_i_reg_924 <= ap_reg_pp0_iter1_exitcond_i_reg_924;
        ap_reg_pp0_iter2_tmp_47_i_reg_934 <= ap_reg_pp0_iter1_tmp_47_i_reg_934;
        ap_reg_pp0_iter2_tmp_last_V_reg_943 <= tmp_last_V_reg_943;
        ap_reg_pp0_iter3_exitcond_i_reg_924 <= ap_reg_pp0_iter2_exitcond_i_reg_924;
        ap_reg_pp0_iter3_p_Val2_2_reg_964 <= p_Val2_2_reg_964;
        ap_reg_pp0_iter3_p_Val2_3_reg_974 <= p_Val2_3_reg_974;
        ap_reg_pp0_iter3_signbit_reg_957 <= signbit_reg_957;
        ap_reg_pp0_iter3_soft_src_V_reg_948 <= soft_src_V_reg_948;
        ap_reg_pp0_iter3_tmp_47_i_reg_934 <= ap_reg_pp0_iter2_tmp_47_i_reg_934;
        ap_reg_pp0_iter3_tmp_last_V_reg_943 <= ap_reg_pp0_iter2_tmp_last_V_reg_943;
        ap_reg_pp0_iter4_Range1_all_ones_1_reg_1035 <= Range1_all_ones_1_reg_1035;
        ap_reg_pp0_iter4_Range1_all_ones_reg_1018 <= Range1_all_ones_reg_1018;
        ap_reg_pp0_iter4_Range1_all_zeros_1_reg_1042 <= Range1_all_zeros_1_reg_1042;
        ap_reg_pp0_iter4_Range1_all_zeros_reg_1025 <= Range1_all_zeros_reg_1025;
        ap_reg_pp0_iter4_Range2_all_ones_1_reg_1030 <= Range2_all_ones_1_reg_1030;
        ap_reg_pp0_iter4_Range2_all_ones_reg_1013 <= Range2_all_ones_reg_1013;
        ap_reg_pp0_iter4_exitcond_i_reg_924 <= ap_reg_pp0_iter3_exitcond_i_reg_924;
        ap_reg_pp0_iter4_not_s_i_i_i_reg_1006 <= not_s_i_i_i_reg_1006;
        ap_reg_pp0_iter4_signbit_reg_957 <= ap_reg_pp0_iter3_signbit_reg_957;
        ap_reg_pp0_iter4_soft_src_V_reg_948 <= ap_reg_pp0_iter3_soft_src_V_reg_948;
        ap_reg_pp0_iter4_tmp_47_i_reg_934 <= ap_reg_pp0_iter3_tmp_47_i_reg_934;
        ap_reg_pp0_iter4_tmp_last_V_reg_943 <= ap_reg_pp0_iter3_tmp_last_V_reg_943;
        ap_reg_pp0_iter5_Range1_all_ones_1_reg_1035 <= ap_reg_pp0_iter4_Range1_all_ones_1_reg_1035;
        ap_reg_pp0_iter5_Range1_all_ones_reg_1018 <= ap_reg_pp0_iter4_Range1_all_ones_reg_1018;
        ap_reg_pp0_iter5_exitcond_i_reg_924 <= ap_reg_pp0_iter4_exitcond_i_reg_924;
        ap_reg_pp0_iter5_p_Val2_5_reg_1047 <= p_Val2_5_reg_1047;
        ap_reg_pp0_iter5_p_Val2_6_reg_1053 <= p_Val2_6_reg_1053;
        ap_reg_pp0_iter5_signbit_reg_957 <= ap_reg_pp0_iter4_signbit_reg_957;
        ap_reg_pp0_iter5_tmp_47_i_reg_934 <= ap_reg_pp0_iter4_tmp_47_i_reg_934;
        ap_reg_pp0_iter5_tmp_last_V_reg_943 <= ap_reg_pp0_iter4_tmp_last_V_reg_943;
        ap_reg_pp0_iter6_exitcond_i_reg_924 <= ap_reg_pp0_iter5_exitcond_i_reg_924;
        ap_reg_pp0_iter6_overflow_1_reg_1099 <= overflow_1_reg_1099;
        ap_reg_pp0_iter6_p_Val2_6_reg_1053 <= ap_reg_pp0_iter5_p_Val2_6_reg_1053;
        ap_reg_pp0_iter6_tmp_47_i_reg_934 <= ap_reg_pp0_iter5_tmp_47_i_reg_934;
        ap_reg_pp0_iter6_tmp_last_V_reg_943 <= ap_reg_pp0_iter5_tmp_last_V_reg_943;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter4_exitcond_i_reg_924))) begin
        carry_1_reg_1088 <= carry_1_fu_563_p2;
        overflow_1_reg_1099 <= overflow_1_fu_656_p2;
        tmp_45_i5_reg_1110 <= tmp_45_i5_fu_688_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == tmp_i_74_reg_903) & (1'd0 == ap_reg_pp0_iter4_exitcond_i_reg_924))) begin
        carry_reg_1083 <= carry_fu_539_p2;
        overflow_reg_1093 <= overflow_fu_629_p2;
        tmp_43_i4_reg_1105 <= tmp_43_i4_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_block_state1 == 1'b0))) begin
        fec_type_read_reg_882 <= fec_type_dout;
        n_read_reg_876 <= n_dout;
        soft_words_tx_read_reg_887 <= soft_words_tx_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))))) begin
        i_reg_928 <= i_fu_317_p2;
        s_i_2_load_reg_918 <= s_i_2_fu_190;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == tmp_i_74_reg_903) & (1'd0 == ap_reg_pp0_iter5_exitcond_i_reg_924))) begin
        ldpc_soft_V_reg_1122 <= ldpc_soft_V_fu_764_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter3_exitcond_i_reg_924))) begin
        newsignbit_2_reg_1066 <= p_Val2_6_fu_491_p2[32'd7];
        p_Val2_6_reg_1053 <= p_Val2_6_fu_491_p2;
        tmp_23_reg_1078 <= tmp_23_fu_516_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == tmp_i_74_reg_903) & (1'd0 == ap_reg_pp0_iter3_exitcond_i_reg_924))) begin
        newsignbit_reg_1059 <= p_Val2_5_fu_482_p2[32'd5];
        p_Val2_5_reg_1047 <= p_Val2_5_fu_482_p2;
        tmp_22_reg_1073 <= tmp_22_fu_512_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter1_exitcond_i_reg_924) & (1'd1 == tmp_i_74_reg_903))) begin
        p_Result_10_i_reg_979 <= {{soft_src_V_fu_344_p2[15:11]}};
        p_Result_11_i_reg_984 <= {{soft_src_V_fu_344_p2[15:10]}};
        p_Val2_2_reg_964 <= {{soft_src_V_fu_344_p2[9:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter1_exitcond_i_reg_924))) begin
        p_Result_15_i_reg_990 <= {{soft_src_V_fu_344_p2[15:13]}};
        p_Result_16_i_reg_995 <= {{soft_src_V_fu_344_p2[15:12]}};
        p_Val2_3_reg_974 <= {{soft_src_V_fu_344_p2[11:4]}};
        signbit_reg_957 <= soft_src_V_fu_344_p2[32'd15];
        soft_src_V_reg_948 <= soft_src_V_fu_344_p2;
        tmp_15_reg_969 <= tmp_15_fu_367_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_i_reg_1136 <= s_i_fu_846_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sel_tmp1_reg_913 <= sel_tmp1_fu_304_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (ap_block_state2_io == 1'b0))) begin
        tmp_29_i_reg_909 <= tmp_29_i_fu_299_p2;
        tmp_i_74_reg_903 <= tmp_i_74_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_30_i_reg_1132 <= tmp_30_i_fu_841_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == exitcond_i_fu_312_p2))) begin
        tmp_47_i_reg_934 <= tmp_47_i_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd0 == exitcond_i_reg_924) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))))) begin
        tmp_V_reg_938 <= soft_data_i_V_V_dout;
        tmp_last_V_reg_943 <= tmp_last_V_fu_340_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd0 == ap_reg_pp0_iter5_exitcond_i_reg_924))) begin
        underflow_1_reg_1115 <= underflow_1_fu_752_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_CS_fsm_state14) & (ap_block_state14_io == 1'b0) & ((1'd1 == tmp_32_i_fu_871_p2) | (1'd1 == tmp_30_i_reg_1132))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_enable_reg_pp0_iter4) & (1'b0 == ap_enable_reg_pp0_iter5) & (1'b0 == ap_enable_reg_pp0_iter6) & (1'b0 == ap_enable_reg_pp0_iter7))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (ap_block_state14_io == 1'b0) & ((1'd1 == tmp_32_i_fu_871_p2) | (1'd1 == tmp_30_i_reg_1132)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_soft_data_TREADY)) begin
        ap_sig_ioackin_soft_data_TREADY = soft_data_TREADY;
    end else begin
        ap_sig_ioackin_soft_data_TREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_soft_words_TREADY)) begin
        ap_sig_ioackin_soft_words_TREADY = soft_words_TREADY;
    end else begin
        ap_sig_ioackin_soft_words_TREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        fec_type_blk_n = fec_type_empty_n;
    end else begin
        fec_type_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_block_state1 == 1'b0))) begin
        fec_type_read = 1'b1;
    end else begin
        fec_type_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond_i_reg_924))) begin
        i_i_phi_fu_258_p4 = i_reg_928;
    end else begin
        i_i_phi_fu_258_p4 = i_i_reg_254;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        n_blk_n = n_empty_n;
    end else begin
        n_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_block_state1 == 1'b0))) begin
        n_read = 1'b1;
    end else begin
        n_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op160_write_state14))) begin
        soft_data_TDATA = data_out_V_1_fu_862_p3;
    end else if (((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)))) begin
        soft_data_TDATA = data_out_V_fu_832_p3;
    end else begin
        soft_data_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934)) | ((1'b1 == ap_CS_fsm_state14) & (1'd0 == tmp_30_i_reg_1132) & (1'd1 == tmp_32_i_fu_871_p2)))) begin
        soft_data_TDATA_blk_n = soft_data_TREADY;
    end else begin
        soft_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op160_write_state14))) begin
        soft_data_TLAST = 1'd1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)))) begin
        soft_data_TLAST = ap_reg_pp0_iter6_tmp_last_V_reg_943;
    end else begin
        soft_data_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) & (1'b0 == ap_reg_ioackin_soft_data_TREADY)) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op160_write_state14) & (1'b0 == ap_reg_ioackin_soft_data_TREADY)))) begin
        soft_data_TVALID = 1'b1;
    end else begin
        soft_data_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond_i_reg_924))) begin
        soft_data_i_V_V_blk_n = soft_data_i_V_V_empty_n;
    end else begin
        soft_data_i_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond_i_reg_924) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))))) begin
        soft_data_i_V_V_read = 1'b1;
    end else begin
        soft_data_i_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (tmp_i_fu_289_p2 == 1'd1)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & (1'd1 == tmp_29_i_reg_909) & (1'd1 == ap_reg_pp0_iter6_tmp_last_V_reg_943)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & (1'd1 == tmp_29_i_reg_909) & (ap_reg_pp0_iter6_tmp_last_V_reg_943 == 1'd0)) | ((1'd1 == tmp_29_i_reg_909) & (1'b1 == ap_CS_fsm_state14) & (1'd0 == tmp_30_i_reg_1132) & (1'd1 == tmp_32_i_fu_871_p2)))) begin
        soft_words_TDATA_blk_n = soft_words_TREADY;
    end else begin
        soft_words_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op143_write_state11) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)))) begin
        soft_words_TLAST = 1'd0;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (tmp_i_fu_289_p2 == 1'd1)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op145_write_state11) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5))) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op162_write_state14)))) begin
        soft_words_TLAST = 1'd1;
    end else begin
        soft_words_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (tmp_i_fu_289_p2 == 1'd1) & (1'b0 == ap_reg_ioackin_soft_words_TREADY)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op143_write_state11) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) & (1'b0 == ap_reg_ioackin_soft_words_TREADY)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_predicate_op145_write_state11) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) & (1'b0 == ap_reg_ioackin_soft_words_TREADY)) | ((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_predicate_op162_write_state14) & (1'b0 == ap_reg_ioackin_soft_words_TREADY)))) begin
        soft_words_TVALID = 1'b1;
    end else begin
        soft_words_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        soft_words_tx_blk_n = soft_words_tx_empty_n;
    end else begin
        soft_words_tx_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_block_state1 == 1'b0))) begin
        soft_words_tx_read = 1'b1;
    end else begin
        soft_words_tx_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((ap_block_state1 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((ap_block_state2_io == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter7) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (ap_enable_reg_pp0_iter6 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == exitcond_i_fu_312_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter7) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (ap_enable_reg_pp0_iter6 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state5)) | ((1'b1 == ap_enable_reg_pp0_iter7) & (1'b1 == ap_block_state11_io))) & (1'd1 == exitcond_i_fu_312_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            if ((1'd0 == tmp_30_i_fu_841_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((ap_block_state14_io == 1'b0) & ((1'd1 == tmp_32_i_fu_871_p2) | (1'd1 == tmp_30_i_reg_1132)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'd0 == tmp_30_i_reg_1132) & (ap_block_state14_io == 1'b0) & (1'd0 == tmp_32_i_fu_871_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_1_fu_451_p2 = ((p_Result_16_i_reg_995 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_436_p2 = ((p_Result_11_i_reg_984 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_1_fu_456_p2 = ((p_Result_16_i_reg_995 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_441_p2 = ((p_Result_11_i_reg_984 == 6'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_1_fu_446_p2 = ((p_Result_15_i_reg_990 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_431_p2 = ((p_Result_10_i_reg_979 == 5'd31) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1) | (1'b0 == n_empty_n) | (1'b0 == fec_type_empty_n) | (1'b0 == soft_words_tx_empty_n));
end

always @ (*) begin
    ap_block_state11_io = (((1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & (1'b0 == ap_sig_ioackin_soft_data_TREADY)) | ((1'b0 == ap_sig_ioackin_soft_words_TREADY) & (1'b1 == ap_predicate_op143_write_state11)) | ((1'b0 == ap_sig_ioackin_soft_words_TREADY) & (1'b1 == ap_predicate_op145_write_state11)));
end

always @ (*) begin
    ap_block_state14_io = (((1'b0 == ap_sig_ioackin_soft_data_TREADY) & (1'b1 == ap_predicate_op160_write_state14)) | ((1'b0 == ap_sig_ioackin_soft_words_TREADY) & (1'b1 == ap_predicate_op162_write_state14)));
end

always @ (*) begin
    ap_block_state2_io = ((tmp_i_fu_289_p2 == 1'd1) & (1'b0 == ap_sig_ioackin_soft_words_TREADY));
end

always @ (*) begin
    ap_block_state5 = ((1'd0 == exitcond_i_reg_924) & (1'b0 == soft_data_i_V_V_empty_n));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op143_write_state11 = ((1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & (1'd1 == tmp_29_i_reg_909) & (ap_reg_pp0_iter6_tmp_last_V_reg_943 == 1'd0));
end

always @ (*) begin
    ap_predicate_op145_write_state11 = ((1'd1 == ap_reg_pp0_iter6_tmp_47_i_reg_934) & (1'd1 == tmp_29_i_reg_909) & (1'd1 == ap_reg_pp0_iter6_tmp_last_V_reg_943));
end

always @ (*) begin
    ap_predicate_op160_write_state14 = ((1'd0 == tmp_30_i_reg_1132) & (1'd1 == tmp_32_i_fu_871_p2));
end

always @ (*) begin
    ap_predicate_op162_write_state14 = ((1'd1 == tmp_29_i_reg_909) & (1'd0 == tmp_30_i_reg_1132) & (1'd1 == tmp_32_i_fu_871_p2));
end

assign brmerge2_i_fu_781_p2 = (ap_reg_pp0_iter6_overflow_1_reg_1099 | underflow_5_not_i_fu_776_p2);

assign brmerge40_demorgan_i_1_fu_661_p2 = (newsignbit_2_reg_1066 & deleted_ones_1_fu_611_p3);

assign brmerge40_demorgan_i_fu_634_p2 = (newsignbit_reg_1059 & deleted_ones_fu_593_p3);

assign brmerge40_i1_i_fu_666_p2 = (brmerge40_demorgan_i_1_fu_661_p2 ^ 1'd1);

assign brmerge40_i_i_fu_639_p2 = (brmerge40_demorgan_i_fu_634_p2 ^ 1'd1);

assign brmerge_i1_i_fu_651_p2 = (newsignbit_2_reg_1066 | p_not_i1_i_fu_645_p2);

assign brmerge_i_fu_735_p2 = (overflow_reg_1093 | underflow_4_not_i_fu_729_p2);

assign brmerge_i_i1_i_fu_772_p2 = (underflow_1_reg_1115 | ap_reg_pp0_iter6_overflow_1_reg_1099);

assign brmerge_i_i_fu_624_p2 = (newsignbit_reg_1059 | p_not_i_i_fu_618_p2);

assign brmerge_i_i_i_fu_724_p2 = (underflow_fu_719_p2 | overflow_reg_1093);

assign carry_1_fu_563_p2 = (tmp_17_fu_527_p3 & tmp_37_i_fu_558_p2);

assign carry_fu_539_p2 = (tmp_16_fu_520_p3 & tmp_36_i_fu_534_p2);

assign data_out_V_1_fu_862_p3 = {{8'd0}, {p_Result_i_fu_852_p4}};

assign data_out_V_fu_832_p3 = {{p_Repl2_s_fu_814_p3}, {p_Result_19_i_fu_822_p4}};

assign deleted_ones_1_fu_611_p3 = ((carry_1_fu_563_p2[0:0] === 1'b1) ? p_41_i1_i_fu_606_p2 : ap_reg_pp0_iter4_Range1_all_ones_1_reg_1035);

assign deleted_ones_fu_593_p3 = ((carry_fu_539_p2[0:0] === 1'b1) ? p_41_i_i_fu_588_p2 : ap_reg_pp0_iter4_Range1_all_ones_reg_1018);

assign deleted_zeros_1_fu_576_p3 = ((carry_1_fu_563_p2[0:0] === 1'b1) ? ap_reg_pp0_iter4_Range1_all_ones_1_reg_1035 : ap_reg_pp0_iter4_Range1_all_zeros_1_reg_1042);

assign deleted_zeros_fu_552_p3 = ((carry_fu_539_p2[0:0] === 1'b1) ? ap_reg_pp0_iter4_Range1_all_ones_reg_1018 : ap_reg_pp0_iter4_Range1_all_zeros_reg_1025);

assign exitcond_i_fu_312_p2 = ((i_i_phi_fu_258_p4 == n_read_reg_876) ? 1'b1 : 1'b0);

assign i_fu_317_p2 = (i_i_phi_fu_258_p4 + 32'd1);

assign ldpc_soft_V_fu_764_p3 = ((brmerge_i_fu_735_p2[0:0] === 1'b1) ? p_Val2_3_mux_i_fu_740_p3 : p_Val2_3_i_fu_757_p3);

assign ldpc_soft_ext_V_fu_799_p1 = $signed(ldpc_soft_V_reg_1122);

assign not_s_i_i_i_fu_426_p2 = (signbit_reg_957 ^ 1'd1);

assign overflow_1_fu_656_p2 = (brmerge_i1_i_fu_651_p2 & ap_reg_pp0_iter4_not_s_i_i_i_reg_1006);

assign overflow_fu_629_p2 = (brmerge_i_i_fu_624_p2 & ap_reg_pp0_iter4_not_s_i_i_i_reg_1006);

assign p_38_i1_i_fu_704_p2 = (carry_1_reg_1088 & ap_reg_pp0_iter5_Range1_all_ones_1_reg_1035);

assign p_38_i_i_fu_694_p2 = (carry_reg_1083 & ap_reg_pp0_iter5_Range1_all_ones_reg_1018);

assign p_41_i1_i_fu_606_p2 = (ap_reg_pp0_iter4_Range2_all_ones_1_reg_1030 & tmp_39_i_fu_600_p2);

assign p_41_i_i_fu_588_p2 = (ap_reg_pp0_iter4_Range2_all_ones_reg_1013 & tmp_38_i_fu_582_p2);

assign p_Repl2_s_fu_814_p3 = ((sel_tmp2_fu_809_p2[0:0] === 1'b1) ? p_Val2_5_mux_i_fu_786_p3 : sel_tmp_fu_802_p3);

assign p_Result_19_i_fu_822_p4 = {{p_Val2_9_reg_242[127:8]}};

assign p_Result_i_fu_852_p4 = {{p_Val2_4_reg_274[127:8]}};

assign p_Val2_3_i_fu_757_p3 = ((underflow_fu_719_p2[0:0] === 1'b1) ? 6'd33 : ap_reg_pp0_iter5_p_Val2_5_reg_1047);

assign p_Val2_3_mux_i_fu_740_p3 = ((brmerge_i_i_i_fu_724_p2[0:0] === 1'b1) ? 6'd31 : ap_reg_pp0_iter5_p_Val2_5_reg_1047);

assign p_Val2_5_fu_482_p2 = (tmp_33_i_fu_478_p1 + ap_reg_pp0_iter3_p_Val2_2_reg_964);

assign p_Val2_5_i_fu_793_p3 = ((underflow_1_reg_1115[0:0] === 1'b1) ? 8'd129 : ap_reg_pp0_iter6_p_Val2_6_reg_1053);

assign p_Val2_5_mux_i_fu_786_p3 = ((brmerge_i_i1_i_fu_772_p2[0:0] === 1'b1) ? 8'd127 : ap_reg_pp0_iter6_p_Val2_6_reg_1053);

assign p_Val2_6_fu_491_p2 = (tmp_35_i_fu_487_p1 + ap_reg_pp0_iter3_p_Val2_3_reg_974);

assign p_not_i1_i_fu_645_p2 = (deleted_zeros_1_fu_576_p3 ^ 1'd1);

assign p_not_i_i_fu_618_p2 = (deleted_zeros_fu_552_p3 ^ 1'd1);

assign qb_assign_1_fu_472_p2 = (r_i_i_i_fu_468_p2 & qbit_fu_461_p3);

assign qbit_fu_461_p3 = ap_reg_pp0_iter3_soft_src_V_reg_948[32'd3];

assign r_fu_421_p2 = ((tmp_15_reg_969 != 3'd0) ? 1'b1 : 1'b0);

assign r_i_i_i_fu_468_p2 = (r_reg_1001 | not_s_i_i_i_reg_1006);

assign s_i_1_fu_329_p2 = (s_i_2_fu_190 + 16'd1);

assign s_i_fu_846_p2 = (s_i_2_i_reg_265 + 16'd1);

assign sel_tmp1_fu_304_p2 = (tmp_i_74_reg_903 ^ 1'd1);

assign sel_tmp2_fu_809_p2 = (brmerge2_i_fu_781_p2 & sel_tmp1_reg_913);

assign sel_tmp_fu_802_p3 = ((tmp_i_74_reg_903[0:0] === 1'b1) ? ldpc_soft_ext_V_fu_799_p1 : p_Val2_5_i_fu_793_p3);

assign soft_src_V_fu_344_p2 = (16'd0 - tmp_V_reg_938);

assign soft_words_TDATA = 8'd16;

assign tmp6_fu_747_p2 = (tmp_45_i5_reg_1110 & tmp_41_i_fu_708_p2);

assign tmp_15_fu_367_p1 = soft_src_V_fu_344_p2[2:0];

assign tmp_16_fu_520_p3 = ap_reg_pp0_iter4_soft_src_V_reg_948[32'd9];

assign tmp_17_fu_527_p3 = ap_reg_pp0_iter4_soft_src_V_reg_948[32'd11];

assign tmp_19_fu_545_p3 = ap_reg_pp0_iter4_soft_src_V_reg_948[32'd10];

assign tmp_21_fu_569_p3 = ap_reg_pp0_iter4_soft_src_V_reg_948[32'd12];

assign tmp_22_fu_512_p1 = p_Val2_5_fu_482_p2[4:0];

assign tmp_23_fu_516_p1 = p_Val2_6_fu_491_p2[6:0];

assign tmp_29_i_fu_299_p2 = ((soft_words_tx_read_reg_887 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_30_i_fu_841_p2 = ((s_i_2_load_reg_918 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_32_i_fu_871_p2 = ((s_i_reg_1136 == 16'd16) ? 1'b1 : 1'b0);

assign tmp_33_i_fu_478_p1 = qb_assign_1_fu_472_p2;

assign tmp_35_i_fu_487_p1 = qb_assign_1_fu_472_p2;

assign tmp_36_i_fu_534_p2 = (newsignbit_reg_1059 ^ 1'd1);

assign tmp_37_i_fu_558_p2 = (newsignbit_2_reg_1066 ^ 1'd1);

assign tmp_38_i_fu_582_p2 = (tmp_19_fu_545_p3 ^ 1'd1);

assign tmp_39_i_fu_600_p2 = (tmp_21_fu_569_p3 ^ 1'd1);

assign tmp_40_i_fu_698_p2 = (p_38_i_i_fu_694_p2 ^ 1'd1);

assign tmp_41_i_fu_708_p2 = (p_38_i1_i_fu_704_p2 ^ 1'd1);

assign tmp_42_i_fu_672_p2 = ((tmp_22_reg_1073 == 5'd0) ? 1'b1 : 1'b0);

assign tmp_43_i4_fu_677_p2 = (tmp_42_i_fu_672_p2 | brmerge40_i_i_fu_639_p2);

assign tmp_44_i_fu_683_p2 = ((tmp_23_reg_1078 == 7'd0) ? 1'b1 : 1'b0);

assign tmp_45_i5_fu_688_p2 = (tmp_44_i_fu_683_p2 | brmerge40_i1_i_fu_666_p2);

assign tmp_47_i_fu_323_p2 = ((s_i_2_fu_190 == 16'd15) ? 1'b1 : 1'b0);

assign tmp_fu_714_p2 = (tmp_43_i4_reg_1105 & tmp_40_i_fu_698_p2);

assign tmp_i_74_fu_294_p2 = ((fec_type_read_reg_882 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_i_fu_289_p2 = ((soft_words_tx_read_reg_887 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_last_V_fu_340_p2 = ((i_reg_928 == n_read_reg_876) ? 1'b1 : 1'b0);

assign underflow_1_fu_752_p2 = (tmp6_fu_747_p2 & ap_reg_pp0_iter5_signbit_reg_957);

assign underflow_4_not_i_fu_729_p2 = (underflow_fu_719_p2 ^ 1'd1);

assign underflow_5_not_i_fu_776_p2 = (underflow_1_reg_1115 ^ 1'd1);

assign underflow_fu_719_p2 = (tmp_fu_714_p2 & ap_reg_pp0_iter5_signbit_reg_957);

endmodule //compress_soft
